/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'Zenith Z-386 MFM-300 Monitor, Version 3.2C'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 7 */
#pragma pack(push, 1)
struct ZBIOS_Label
{
  unsigned __int8 Row_Y __udec;
  unsigned __int8 Column_X __udec;
  void *text_offset __offset(OFF16|AUTO);
};
#pragma pack(pop)

/* 108 */
enum IO_Ports : unsigned __int16
{
  IO_Port_00h_Dummy_empty_value = 0x0,
  IO_Port_00h_DMA1_Ch0_Address = 0x0,
  IO_Port_01h_DMA1_Ch0_Count = 0x1,
  IO_Port_02h_DMA1_Ch1_Address = 0x2,
  IO_Port_03h_DMA1_Ch1_Count = 0x3,
  IO_Port_04h_DMA1_Ch2_Address = 0x4,
  IO_Port_05h_DMA1_Ch2_Count = 0x5,
  IO_Port_06h_DMA1_Ch3_Address = 0x6,
  IO_Port_07h_DMA1_Ch3_Count = 0x7,
  IO_Port_08h_DMA1_Command = 0x8,
  IO_Port_08h_DMA1_Status = 0x8,
  IO_Port_09h_DMA1_Write_Request = 0x9,
  IO_Port_0Ah_DMA1_Single_Mask = 0xA,
  IO_Port_0Bh_DMA1_Mode = 0xB,
  IO_Port_0Ch_DMA1_Clear_FlipFlop = 0xC,
  IO_Port_0Dh_DMA1_Master_Clear = 0xD,
  IO_Port_0Eh_DMA1_Clear_Mask = 0xE,
  IO_Port_0Fh_DMA1_Write_All_Mask = 0xF,
  IO_Port_20h_PIC1_Command = 0x20,
  IO_Port_21h_PIC1_Interrupt_Mask = 0x21,
  IO_Port_40h_PIT_Counter0 = 0x40,
  IO_Port_41h_PIT_Counter1 = 0x41,
  IO_Port_42h_PIT_Counter2 = 0x42,
  IO_Port_43h_PIT_Control_Word = 0x43,
  IO_Port_60h_KBD_Command = 0x60,
  IO_Port_60h_KBD_Data = 0x60,
  IO_Port_61h_FE3001A_Parity = 0x61,
  IO_Port_64h_KBC_Command = 0x64,
  IO_Port_64h_KBC_Status = 0x64,
  IO_Port_70h_CMOS_Index = 0x70,
  IO_Port_71h_CMOS_Data = 0x71,
  IO_Port_72h_FE3001_Command_Index = 0x72,
  IO_Port_73h_FE3001_Command_Data = 0x73,
  IO_Port_80h_POST_Code = 0x80,
  IO_Port_81h_DMA_Page_Ch2 = 0x81,
  IO_Port_82h_DMA_Page_Ch3 = 0x82,
  IO_Port_83h_DMA_Page_Ch1 = 0x83,
  IO_Port_87h_DMA_Page_Ch0 = 0x87,      ///< Channel 0 Page Address Register (unusable)
  IO_Port_89h_DMA_Page_Ch6 = 0x89,
  IO_Port_8Ah_DMA_Page_Ch7 = 0x8A,
  IO_Port_8Bh_DMA_Page_Ch5 = 0x8B,
  IO_Port_8Fh_DMA_Page_Ch4 = 0x8F,      ///< Channel 4 Page Address Register (unusable)
  IO_Port_8Ch_Zenith_Diagnostic_LED = 0x8C,
  IO_Port_A0h_PIC2_Command = 0xA0,
  IO_Port_A1h_PIC2_Interrupt_Mask = 0xA1,
  IO_Port_C0h_DMA2_Ch4_Address = 0xC0,  ///< Cascade channel address (unusable)
  IO_Port_C2h_DMA2_Ch4_Count = 0xC2,    ///< Cascade channel count (unusable)
  IO_Port_C4h_DMA2_Ch5_Address = 0xC4,
  IO_Port_C6h_DMA2_Ch5_Count = 0xC6,
  IO_Port_C8h_DMA2_Ch6_Address = 0xC8,
  IO_Port_CAh_DMA2_Ch6_Count = 0xCA,
  IO_Port_CCh_DMA2_Ch7_Address = 0xCC,
  IO_Port_CEh_DMA2_Ch7_Count = 0xCE,
  IO_Port_D0h_DMA2_Command = 0xD0,
  IO_Port_D0h_DMA2_Status = 0xD0,
  IO_Port_D2h_DMA2_Write_Request = 0xD2,
  IO_Port_D4h_DMA2_Single_Mask = 0xD4,
  IO_Port_D6h_DMA2_Mode = 0xD6,
  IO_Port_D8h_DMA2_Clear_FlipFlop = 0xD8,
  IO_Port_DAh_DMA2_Master_Clear = 0xDA,
  IO_Port_DCh_DMA2_Clear_Mask = 0xDC,
  IO_Port_DEh_DMA2_Write_All_Mask = 0xDE,
  IO_Port_1F0h_IDE_0_Data = 0x1F0,
  IO_Port_1F1h_IDE_0_Error_Precomp = 0x1F1,
  IO_Port_1F2h_IDE_0_Sector_Count = 0x1F2,
  IO_Port_1F3h_IDE_0_Sector_Number = 0x1F3,
  IO_Port_1F4h_IDE_0_Cylinder_Low = 0x1F4,
  IO_Port_1F5h_IDE_0_Cylinder_High = 0x1F5,
  IO_Port_1F6h_IDE_0_Drive_Head = 0x1F6,
  IO_Port_1F7h_IDE_0_Command = 0x1F7,
  IO_Port_1F7h_IDE_0_Status = 0x1F7,
  IO_Port_201h_Gameport = 0x201,
  IO_Port_332h_Zenith_mystery_Data = 0x332,
  IO_Port_330h_Zenith_mystery_transfer_length_low = 0x330,
  IO_Port_331h_Zenith_mystery_transfer_length_high = 0x331,
  IO_Port_333h_Zenith_mystery_Command = 0x333,
  IO_Port_334h_Zenith_unknown = 0x334,
  IO_Port_335h_Zenith_unknown = 0x335,
  IO_Port_336h_Zenith_unknown = 0x336,
  IO_Port_337h_Zenith_mystery_Status = 0x337,
  IO_Port_338h_Zenith_unknown = 0x338,
  IO_Port_339h_Zenith_unknown = 0x339,
  IO_Port_33Bh_Zenith_unknown = 0x33B,
  IO_Port_33Ch_Zenith_unknown = 0x33C,
  IO_Port_3B4h_CRTC_Index_Mono = 0x3B4,
  IO_Port_3B5h_CRTC_Data_Mono = 0x3B5,
  IO_Port_3B8h_CRTC_Mode_Control_Mono = 0x3B8,
  IO_Port_3B9h_CRTC_Feature_Control_Mono = 0x3B9,
  IO_Port_3BAh_CRTC_Status_Mono = 0x3BA,
  IO_Port_3D4h_CRTC_Index_CGA = 0x3D4,
  IO_Port_3D5h_CRTC_Data = 0x3D5,
  IO_Port_3D8h_CRTC_Mode_Control = 0x3D8,
  IO_Port_3D9h_CGA_Color_Control = 0x3D9,
  IO_Port_3DAh_CRTC_Status = 0x3DA,
  IO_Port_3DBh_CRTC_LightPen_Reset = 0x3DB,
  IO_Port_3F0h_FDC_Status_A = 0x3F0,
  IO_Port_3F1h_FDC_Status_B = 0x3F1,
  IO_Port_3F2h_FDC_Digital_Output = 0x3F2,
  IO_Port_3F3h_FDC_Tape_Drive = 0x3F3,
  IO_Port_3F4h_FDD_Main_Status = 0x3F4,
  IO_Port_3F4h_FDC_Data_Rate_Select = 0x3F4,
  IO_Port_3F5h_FDD_Command = 0x3F5,
  IO_Port_3F5h_FDD_Data = 0x3F5,
  IO_Port_3F6h_IDE_0_Dev_Control = 0x3F6,
  IO_Port_3F6h_IDE_0_Alt_Status = 0x3F6,
  IO_Port_3F7h_IDE_0_Drive_Address = 0x3F7,
  IO_Port_3F7h_FDC_Digital_Input_AT = 0x3F7,
  IO_Port_3F7h_FDC_Config_Control = 0x3F7,
  IO_Port_3F8h_COM1_Base = 0x3F8,
  IO_Port_3F8h_UART_Divisor_Latch_LSB = 0x3F8,
  IO_Port_3F9h_UART_Divisor_Latch_MSB = 0x3F9,
  IO_Port_3F9h_UART_Interrupt_Enable = 0x3F9,
  IO_Port_3FAh_UART_Interrupt_Ident = 0x3FA,
  IO_Port_3FBh_UART_Line_Control = 0x3FB,
  IO_Port_3FCh_UART_Modem_Control = 0x3FC,
  IO_Port_3FDh_UART_Line_Status = 0x3FD,
  IO_Port_3FEh_UART_Modem_Status = 0x3FE,
  IO_Port_2F8h_COM2_Base = 0x2F8,
  IO_Port_3E8h_COM3_Base = 0x3E8,
  IO_Port_2E8h_COM4_Base = 0x2E8,
  IO_Port_378h_LPT1_Base = 0x378,
  IO_Port_379h_LPT1_Status = 0x379,
  IO_Port_37Ah_LPT1_Control = 0x37A,
  IO_Port_278h_LPT2_Base = 0x278,
  IO_Port_3BCh_LPT3_Base = 0x3BC,
  IO_Port_EDh_Zenith_unknown = 0xED,
  IO_Port_F0h_Zenith_unknown = 0xF0,
  IO_Port_F1h_Zenith_unknown = 0xF1,
  IO_Port_213h_Zenith_unknown = 0x213,
};

/* 15 */
#pragma pack(push, 1)
struct port_init
{
  IO_Ports port;
  unsigned __int8 value;
};
#pragma pack(pop)

/* 16 */
#pragma pack(push, 1)
struct __unaligned __declspec(align(1)) cmd_lookup
{
  unsigned __int8 key __char;
  void *address __offset(OFF16|AUTO);
};
#pragma pack(pop)

/* 17 */
#pragma pack(push, 1)
struct OpcodeDescriptor
{
  void *mnemonic_token __offset(OFF16|AUTO);
  unsigned __int16 operand_flags;
};
#pragma pack(pop)

/* 19 */
#pragma pack(push, 1)
struct reg_table
{
  unsigned __int16 len __udec;
  port_init port_value[];
};
#pragma pack(pop)

/* 21 */
#pragma pack(push, 1)
struct data_pair
{
  unsigned __int8 offset;
  unsigned __int8 data;
};
#pragma pack(pop)

/* 22 */
#pragma pack(push, 1)
struct data_table
{
  __int16 len;
  data_pair offset_data[];
};
#pragma pack(pop)

/* 24 */
#pragma pack(push, 1)
struct __unaligned __declspec(align(1)) some_table1
{
  __int16 check;
  unsigned __int8 data0;
  unsigned __int8 data1;
  unsigned __int8 data2;
  unsigned __int8 data3;
  unsigned __int8 data4;
  unsigned __int8 data5;
  unsigned __int8 data6;
};
#pragma pack(pop)

/* 167 */
enum __bitmask __bin __lzero IO_Port_201h_Gameport : unsigned __int8
{
  JOY_AXES_MASK = 0x0F,                 ///< MASK
  JOY_A_X = 0b00000001,
  JOY_A_Y = 0b00000010,
  JOY_B_X = 0b00000100,
  JOY_B_Y = 0b00001000,
  JOY_ALL_BUTTONS = 0xF0,               ///< MASK
  JOY_A_BUTTON_1 = 0b00010000,
  JOY_A_BUTTON_2 = 0b00100000,
  JOY_B_BUTTON_1 = 0b01000000,
  JOY_B_BUTTON_2 = 0b10000000,
};

/* 26 */
#pragma pack(push, 1)
struct joy_lookup
{
  IO_Port_201h_Gameport mask;
  __int16 disable_timeout_zeroing;
  unsigned __int8 end_marker;
};
#pragma pack(pop)

/* 66 */
enum int13h_status_errors : unsigned __int8
{
  int13h_0_status_success = 0x0,
  int13h_1_status_bad_command = 0x1,
  int13h_2_status_address_mark_not_found = 0x2,
  int13h_3_status_write_protected = 0x3,
  int13h_4_status_sector_not_found = 0x4,
  int13h_5_status_reset_failed = 0x5,
  int13h_6_status_disk_changed = 0x6,
  int13h_7_status_bad_fixed_disk_parameter_table = 0x7,
  int13h_8_status_DMA_overrun = 0x8,
  int13h_9_status_data_boundary_error = 0x9,
  int13h_A_status_bad_harddisk_sector_detected = 0xA,
  int13h_B_status_bad_harddisk_track_detected = 0xB,
  int13h_C_status_unsupported_track_or_invalid_media = 0xC,
  int13h_D_status_invalid_number_of_sectors_on_harddisk_format = 0xD,
  int13h_E_status_harddisk_control_data_address_mark_detected = 0xE,
  int13h_F_status_harddisk_DMA_arbitration_level_out_of_range = 0xF,
  int13h_10_status_CRC_or_ECC_error_on_read = 0x10,
  int13h_11_status_harddisk_data_ECC_corrected = 0x11,
  int13h_20_status_controller_failure = 0x20,
  int13h_31_status_no_media_in_drive_IBM_MS_INT_13_extensions = 0x31,
  int13h_32_status_incorrect_drive_type_stored_in_CMOS_Compaq = 0x32,
  int13h_40_status_seek_failed = 0x40,
  int13h_80_status_timeout_not_ready = 0x80,
  int13h_AA_status_harddisk_drive_not_ready = 0xAA,
  int13h_B0_status_volume_not_locked_in_drive_INT_13_extensions = 0xB0,
  int13h_B1_status_volume_locked_in_drive_INT_13_extensions = 0xB1,
  int13h_B2_status_volume_not_removable_INT_13_extensions = 0xB2,
  int13h_B3_status_volume_in_use_INT_13_extensions = 0xB3,
  int13h_B4_status_lock_count_exceeded_INT_13_extensions = 0xB4,
  int13h_B5_status_valid_eject_request_failed_INT_13_extensions = 0xB5,
  int13h_B6_status_volume_present_but_read_protected_INT_13_extensions = 0xB6,
  int13h_BB_status_harddisk_undefined_error = 0xBB,
  int13h_CC_status_harddisk_write_fault = 0xCC,
  int13h_E0_status_harddisk_status_register_error = 0xE0,
  int13h_FF_status_sense_operation_failed = 0xFF,
};

/* 27 */
#pragma pack(push, 1)
struct compare_pair
{
  unsigned __int8 index;
  int13h_status_errors error;
};
#pragma pack(pop)

/* 29 */
#pragma pack(push, 1)
struct GDT_descriptor
{
  unsigned __int16 limit_low;
  unsigned __int16 base_low;
  unsigned __int8 base_mid;
  unsigned __int8 access;
  unsigned __int8 flags_limit;
  unsigned __int8 base_high;
};
#pragma pack(pop)

/* 30 */
#pragma pack(push, 1)
struct __unaligned __declspec(align(2)) SystemTablePointer
{
  unsigned __int16 gdt_limit;
  unsigned int gdt_base __offset(OFF32|RVAOFF);
};
#pragma pack(pop)

/* 31 */
#pragma pack(push, 1)
struct disk_error
{
  unsigned __int8 num;
  void *address __offset(OFF16|AUTO);
};
#pragma pack(pop)

/* 32 */
#pragma pack(push, 1)
struct struct_F0801
{
  unsigned __int8 mask __bin __lzero;
  __int16 length;
  int pointer;
  int pointer2;
};
#pragma pack(pop)

/* 34 */
#pragma pack(push, 1)
struct Video_timing_table
{
  unsigned __int8 hTotal __udec;
  unsigned __int8 hDisplayed __udec;
  unsigned __int8 hSync __udec;
  unsigned __int8 hvSyncWidth __udec;
  unsigned __int8 vTotal __udec;
  unsigned __int8 vTotalAdjusted __udec;
  unsigned __int8 vDisplayed __udec;
  unsigned __int8 vSync __udec;
  unsigned __int8 Interlace;
  unsigned __int8 maxScanLine __udec;
  unsigned __int8 cursorStart __udec;
  unsigned __int8 cursorEnd __udec;
  _BYTE gap8[4];
};
#pragma pack(pop)

/* 35 */
#pragma pack(push, 1)
struct FDPT
{
  unsigned __int16 Cylinders __udec;
  unsigned __int8 Heads __udec;
  unsigned __int16 reducedWriteCyl __udec;
  unsigned __int16 PrecompCyl __udec;
  unsigned __int8 ECC;
  unsigned __int8 Control;
  unsigned __int8 bTimeOutStd __udec;
  unsigned __int8 bTimeOutFmt __udec;
  unsigned __int8 bTimeOutChk __udec;
  unsigned __int16 landinghZoneCyl __udec;
  unsigned __int8 SectorsPerTrack __udec;
  _BYTE unknown;
};
#pragma pack(pop)

/* 72 */
enum __bitmask __bin __lzero DPT_step_rate_head_unload : unsigned __int8
{
  DPT_step_rate_MASK = 0x0F,            ///< MASK
  DPT_step_rate_16ms = 0b00000000,
  DPT_step_rate_15ms = 0b00000001,
  DPT_step_rate_14ms = 0b00000010,
  DPT_step_rate_13ms = 0b00000011,
  DPT_step_rate_12ms = 0b00000100,
  DPT_step_rate_11ms = 0b00000101,
  DPT_step_rate_10ms = 0b00000110,
  DPT_step_rate_9ms = 0b00000111,
  DPT_step_rate_8ms = 0b00001000,
  DPT_step_rate_7ms = 0b00001001,
  DPT_step_rate_6ms = 0b00001010,
  DPT_step_rate_5ms = 0b00001011,
  DPT_step_rate_4ms = 0b00001100,
  DPT_step_rate_3ms = 0b00001101,
  DPT_step_rate_2ms = 0b00001110,
  DPT_step_rate_1ms = 0b00001111,
  DPT_head_unload_MASK = 0xF0,          ///< MASK
  DPT_head_unload_16ms = 0b00010000,
  DPT_head_unload_32ms = 0b00100000,
  DPT_head_unload_48ms = 0b00110000,
  DPT_head_unload_64ms = 0b01000000,
  DPT_head_unload_80ms = 0b01010000,
  DPT_head_unload_96ms = 0b01100000,
  DPT_head_unload_112ms = 0b01110000,
  DPT_head_unload_128ms = 0b10000000,
  DPT_head_unload_144ms = 0b10010000,
  DPT_head_unload_160ms = 0b10100000,
  DPT_head_unload_176ms = 0b10110000,
  DPT_head_unload_192ms = 0b11000000,
  DPT_head_unload_208ms = 0b11010000,
  DPT_head_unload_224ms = 0b11100000,
  DPT_head_unload_240ms = 0b11110000,
};

/* 74 */
enum __bitmask __bin __lzero DPT_head_load_dma : unsigned __int8
{
  DPT_head_load_time_MASK = 0x7F,       ///< MASK
  DPT_head_load_2ms = 0b00000001,
  DPT_head_load_4ms = 0b00000010,
  DPT_head_load_6ms = 0b00000011,
  DPT_head_load_8ms = 0b00000100,
  DPT_head_load_10ms = 0b00000101,
  DPT_head_load_254ms = 0b01111111,
  DPT_DMA_MASK = 0x80,                  ///< MASK
  DPT_DMA_Mode = 0b00000000,
  DPT_Non_DMA_Mode = 0b00000000,
};

/* 48 */
enum __bin __lzero DPT_bytes_per_sector : unsigned __int8
{
  DPT_bytes_per_sector_128 = 0b00000000,
  DPT_bytes_per_sector_256 = 0b00000001,
  DPT_bytes_per_sector_512 = 0b00000010,
  DPT_bytes_per_sector_1024 = 0b00000011,
};

/* 47 */
enum __bin __lzero DPT_sectors_per_track : unsigned __int8
{
  DPT_sectors_per_track_9 = 0b00001001,
  DPT_sectors_per_track_15 = 0b00001111,
  DPT_sectors_per_track_18 = 0b00010010,
  DPT_sectors_per_track_36 = 0b00100100,
};

/* 36 */
struct DPT
{
  DPT_step_rate_head_unload step_rate_head_unload;
  DPT_head_load_dma head_load_dma;
  unsigned __int8 motor_off_delay __udec;
  DPT_bytes_per_sector bytes_per_sector;
  DPT_sectors_per_track sectors_per_track;
  unsigned __int8 gap_length __udec;
  unsigned __int8 data_length __udec;
  unsigned __int8 gap_length_format __udec;
  unsigned __int8 fill_byte;
  unsigned __int8 head_settle_time __udec;
  unsigned __int8 motor_start_time __udec;
};

/* 38 */
enum __bitmask __bin __lzero int15h_C0h_Features : unsigned __int8
{
  int15h_C0h_Features_Reserved = 0b00000001,
  int15h_C0h_Features_bus_MASK = 0x02,  ///< MASK
  int15h_C0h_Features_PC_bus = 0b00000000,
  int15h_C0h_Features_Micro_Channel = 0b00000010,
  int15h_C0h_Features_Extended_BDA = 0b00000100,
  int15h_C0h_Features_Wait_external_event = 0b00001000,
  int15h_C0h_Features_Keyboard_Intercept = 0b00010000,
  int15h_C0h_Features_RTC = 0b00100000,
  int15h_C0h_Features_second_PIC = 0b01000000,
  int15h_C0h_Features_HDD_DMA3 = 0b10000000,
};

/* 37 */
#pragma pack(push, 1)
struct __unaligned __declspec(align(2)) system_descriptor_table
{
  __int16 len;
  unsigned __int8 model_number;
  unsigned __int8 Sub_model_number;
  unsigned __int8 BIOS_revision_level;
  int15h_C0h_Features Feature_information;
  _BYTE gap6[4];
};
#pragma pack(pop)

/* 39 */
enum __bitmask __bin __lzero BDA_42h_floppy_status_register_ST0 : unsigned __int8
{
  FDC_ST0_DRIVE_MASK = 0x03,            ///< MASK
  FDC_ST0_DRIVE_1 = 0b00000001,         ///< bit0 0 = FDC_ST0_DRIVE_0
  FDC_ST0_DRIVE_2 = 0b00000010,
  FDC_ST0_DRIVE_3 = 0b00000011,
  FDC_ST0_HEAD_1 = 0b00000100,          ///< bit2 0 = FDC_ST0_HEAD_0
  FDC_ST0_NOT_READY = 0b00001000,
  FDC_ST0_FAULT_DETECTED = 0b00010000,
  FDC_ST0_SEEK_COMPLETE = 0b00100000,
  FDC_ST0_INT_MASK = 0xC0,              ///< MASK
  FDC_ST0_INT_ABNORMAL = 0b01000000,
  FDC_ST0_INT_INVALID = 0b10000000,     ///< abnormal termination, ready line on, or diskette changed
  FDC_ST0_INT_SEEK_FAIL = 0b11000000,   ///< seek command not completed
};

/* 76 */
enum __bitmask __bin __lzero BDA_43h_floppy_status_register_ST1 : unsigned __int8
{
  FDC_ST1_MISSING_ADDR_MARK = 0b00000001,
  FDC_ST1_NOT_WRITABLE = 0b00000010,
  FDC_ST1_NO_DATA = 0b00000100,
  FDC_ST1_UNUSED_BIT3 = 0b00001000,
  FDC_ST1_OVERRUN = 0b00010000,
  FDC_ST1_DATA_ERROR = 0b00100000,
  FDC_ST1_UNUSED_BIT6 = 0b01000000,
  FDC_ST1_END_OF_CYLINDER = 0b10000000,
};

/* 40 */
#pragma pack(push, 1)
struct FDD_ST1_to_Error
{
  BDA_43h_floppy_status_register_ST1 err_mask_st1;
  int13h_status_errors err_mask;
};
#pragma pack(pop)

/* 41 */
enum __bitmask __bin __lzero BDA_8Fh_floppy_information : unsigned __int8
{
  floppy_info_drive_0_supports_80_tracks_always_valid = 0b00000001,
  floppy_info_drive_0_multi_rate_valid_if_determined = 0b00000010,
  floppy_info_drive_0_determined = 0b00000100,
  floppy_info_reserved1 = 0b00001000,
  floppy_info_drive_1_supports_80_tracks_always_valid = 0b00010000,
  floppy_info_drive_1_multi_rate_valid_if_determined = 0b00100000,
  floppy_info_drive_1_determined = 0b01000000,
  floppy_info_reserved2 = 0b10000000,
};

/* 58 */
enum __bitmask __bin __lzero BDA_90h_drive0_media_state_RATE : unsigned __int8
{
  FLOPPY_RATE_MASK = 0xC0,              ///< MASK
  FLOPPY_RATE_500KBPS = 0b00000000,
  FLOPPY_RATE_300KBPS = 0b01000000,
  FLOPPY_RATE_250KBPS = 0b10000000,
  FLOPPY_RATE_known_media = 0b00010000,
};

/* 42 */
struct DPTe
{
  DPT DPT;
  unsigned __int8 Maximum_Track __udec;
  BDA_90h_drive0_media_state_RATE rate;
};

/* 52 */
enum IO_Port_3F5h_FDD_Command : unsigned __int8
{
  IO_Port_3F5h_FDC_CMD_SPECIFY = 0x3,
  IO_Port_3F5h_FDC_CMD_RECALIBRATE = 0x7,
  IO_Port_3F5h_FDC_CMD_SENSE_INTERRUPT = 0x8,
  IO_Port_3F5h_FDC_CMD_SEEK = 0xF,
  IO_Port_3F5h_FDC_CMD_READ_DATA = 0x6,
  IO_Port_3F5h_FDC_CMD_READ_DATA_MFM = 0x46,
  IO_Port_3F5h_FDC_CMD_READ_DATA_MT_MFM = 0xC6,
  IO_Port_3F5h_FDC_CMD_READ_DATA_MT_MFM_SkipDeleted = 0xE6,
  IO_Port_3F5h_FDC_CMD_WRITE_DATA = 0x5,
  IO_Port_3F5h_FDC_CMD_WRITE_DATA_MFM = 0x45,
  IO_Port_3F5h_FDC_CMD_WRITE_DATA_MT_MFM = 0xC5,
  IO_Port_3F5h_FDC_CMD_WRITE_DATA_MT_MFM_SkipDeleted = 0xE5,
  IO_Port_3F5h_FDC_CMD_READ_ID = 0xA,
  IO_Port_3F5h_FDC_CMD_READ_ID_MFM = 0x4A,
  IO_Port_3F5h_FDC_CMD_FORMAT_TRACK = 0xD,
  IO_Port_3F5h_FDC_CMD_FORMAT_TRACK_MFM = 0x4D,
  IO_Port_3F5h_FDC_CMD_READ_TRACK = 0x2,
  IO_Port_3F5h_FDC_CMD_READ_TRACK_MFM = 0x42,
  IO_Port_3F5h_FDC_CMD_SENSE_DRIVE_STATUS = 0x4,
  IO_Port_3F5h_FDC_CMD_WRITE_DELETED_DATA = 0x9,
  IO_Port_3F5h_FDC_CMD_READ_DELETED_DATA = 0xC,
  IO_Port_3F5h_FDC_CMD_DUMP_REGISTERS = 0xE,
  IO_Port_3F5h_FDC_CMD_VERSION = 0x10,
  IO_Port_3F5h_FDC_CMD_CONFIGURE = 0x13,
};

/* 55 */
enum IVT_Vectors : unsigned __int8
{
  IVT_SINGLE_STEP = 0x1,
  IVT_NMI = 0x2,
  IVT_BREAKPOINT = 0x3,
  IVT_OVERFLOW = 0x4,
  IVT_PRINT_SCREEN = 0x5,
  IVT_TIMER = 0x8,
  IVT_KEYBOARD = 0x9,
  IVT_FDC = 0xE,
  IVT_VIDEO = 0x10,
  IVT_EQUIPMENT_CHECK = 0x11,
  IVT_MEMORY_SIZE = 0x12,
  IVT_DISK_IO = 0x13,
  IVT_SERIAL_IO = 0x14,
  IVT_SYSTEM_SERVICES = 0x15,
  IVT_KEYBOARD_SERVICES = 0x16,
  IVT_PRINTER_IO = 0x17,
  IVT_BASIC_IO = 0x18,
  IVT_BOOTSTRAP = 0x19,
  IVT_TIME = 0x1A,
  IVT_CTRL_BREAK = 0x1B,
  IVT_TIMER_TICK = 0x1C,
  IVT_Video_Initialization_Table = 0x1D,
  IVT_Diskette_Parameter_Table = 0x1E,
  IVT_VIDEO_CHARS_TABLE = 0x1F,
  IVT_HDD = 0x40,
  IVT_Disk_Parameter_Table1 = 0x41,
  IVT_Disk_Parameter_Table2 = 0x46,
};

/* 57 */
enum BDA_indexes : unsigned __int8
{
  BDA_00h_com_port1 = 0x0,
  BDA_02h_com_port2 = 0x2,
  BDA_04h_com_port3 = 0x4,
  BDA_06h_com_port4 = 0x6,
  BDA_08h_parallel_port1 = 0x8,
  BDA_0Ah_parallel_port2 = 0xA,
  BDA_0Ch_parallel_port3 = 0xC,
  BDA_0Eh_parallel_port4 = 0xE,
  BDA_10h_equipment_list = 0x10,
  BDA_12h_interrupt_flag = 0x12,
  BDA_13h_memory_size_kb = 0x13,
  BDA_15h_debug = 0x15,
  BDA_17h_Keyboard_shift_flags_1 = 0x17,
  BDA_18h_Keyboard_shift_flags_2 = 0x18,
  BDA_19h_Alt_Numpad_work_area = 0x19,
  BDA_1Ah_Keyboard_buffer_head_offset = 0x1A,
  BDA_1Ch_Keyboard_buffer_tail_offset = 0x1C,
  BDA_1Eh_Keyboard_buffer = 0x1E,
  BDA_3Eh_floppy_calibration_status = 0x3E,
  BDA_3Fh_floppy_motor_status = 0x3F,
  BDA_40h_floppy_motor_timeout = 0x40,
  BDA_41h_floppy_status = 0x41,
  BDA_42h_floppy_status_register_ST0 = 0x42,
  BDA_43h_floppy_status_register_ST1 = 0x43,
  BDA_44h_floppy_status_register_ST2 = 0x44,
  BDA_45h_floppy_cylinder_number = 0x45,
  BDA_46h_floppy_head_number = 0x46,
  BDA_47h_floppy_sector_number = 0x47,
  BDA_48h_floppy_bytes_written = 0x48,
  BDA_42h_Zenith_IDE_1F1h_PrecompCyl = 0x42,
  BDA_43h_Zenith_IDE_1F2h_Sector_Count = 0x43,
  BDA_44h_Zenith_IDE_1F3h_Sector_Num = 0x44,
  BDA_45h_Zenith_IDE_1F4h_Cyl_Low = 0x45,
  BDA_46h_Zenith_IDE_1F5h_Cyl_High = 0x46,
  BDA_47h_Zenith_IDE_1F6h_Drive_Head = 0x47,
  BDA_48h_Zenith_IDE_1F7h_Command = 0x48,
  BDA_49h_video_active_mode = 0x49,
  BDA_4Ah_video_columns_per_row = 0x4A,
  BDA_4Ch_video_active_page_size = 0x4C,
  BDA_4Eh_Offset_address_of_active_video_page_in_video_RAM = 0x4E,
  BDA_50h_cursor_pos_page0 = 0x50,
  BDA_51h_cursor_pos_page0_row = 0x51,
  BDA_52h_cursor_pos_page1 = 0x52,
  BDA_54h_cursor_pos_page2 = 0x54,
  BDA_56h_cursor_pos_page3 = 0x56,
  BDA_58h_cursor_pos_page4 = 0x58,
  BDA_5Ah_cursor_pos_page5 = 0x5A,
  BDA_5Ch_cursor_pos_page6 = 0x5C,
  BDA_5Eh_cursor_pos_page7 = 0x5E,
  BDA_60h_cursor_mode = 0x60,
  BDA_62h_video_active_page = 0x62,
  BDA_63h_CRTC_6845_base_address = 0x63,
  BDA_65h_CRTC_Mode_Control = 0x65,
  BDA_66h_palette_or_CGA_color_burst = 0x66,
  BDA_67h_Adapter_ROM_offset_address = 0x67,
  BDA_69h_Adapter_ROM_segment_address = 0x69,
  BDA_6Bh_last_irq = 0x6B,
  BDA_6Ch_Timer_ticks_since_midnight = 0x6C,
  BDA_6Eh_Timer_ticks_since_midnight2 = 0x6E,
  BDA_70h_Timer_24_hour_flag = 0x70,
  BDA_71h_Keyboard_Ctrl_Break_flag = 0x71,
  BDA_72h_soft_reset_flag = 0x72,
  BDA_73h_soft_reset_flag_low_byte = 0x73,
  BDA_74h_HDD_last_op_status = 0x74,
  BDA_75h_HDD_count = 0x75,
  BDA_76h_HDD_ctrl_byte = 0x76,
  BDA_77h_HDD_IO_port = 0x77,
  BDA_78h_parallel_port1_timeout = 0x78,
  BDA_79h_parallel_port2_timeout = 0x79,
  BDA_7Ah_parallel_port3_timeout = 0x7A,
  BDA_7Bh_parallel_port4_timeout_vds = 0x7B,
  BDA_7Ch_serial_port1_timeout = 0x7C,
  BDA_7Dh_serial_port2_timeout = 0x7D,
  BDA_7Eh_serial_port3_timeout = 0x7E,
  BDA_7Fh_serial_port4_timeout = 0x7F,
  BDA_80h_Keyboard_buffer_starting_address = 0x80,
  BDA_82h_Keyboard_buffer_ending_address = 0x82,
  BDA_84h_video_rows = 0x84,
  BDA_85h_scan_lines_per_char = 0x85,
  BDA_87h_video_adapter_options = 0x87,
  BDA_88h_video_adapter_switches = 0x88,
  BDA_89h_VGA_flags_1 = 0x89,
  BDA_8Ah_VGA_flags_2 = 0x8A,
  BDA_8Bh_floppy_cfg_data = 0x8B,
  BDA_8Ch_HDD_CTRL_status = 0x8C,
  BDA_8Dh_HDD_ERROR_byte = 0x8D,
  BDA_8Eh_HDD_task_complete_flag = 0x8E,
  BDA_8Fh_floppy_information = 0x8F,
  BDA_90h_drive0_media_state = 0x90,
  BDA_91h_drive1_media_state = 0x91,
  BDA_92h_drive0_starting_state = 0x92,
  BDA_93h_drive1_starting_state = 0x93,
  BDA_94h_drive0_current_cylinder = 0x94,
  BDA_95h_drive1_current_cylinder = 0x95,
  BDA_96h_keyboard_flags_3 = 0x96,
  BDA_97h_keyboard_flags_4 = 0x97,
  BDA_98h_User_wait_pointer_Offset = 0x98,
  BDA_9Ah_User_wait_pointer_Segment = 0x9A,
  BDA_9Ch_User_wait_count_lower = 0x9C,
  BDA_9Eh_User_wait_count_upper = 0x9E,
  BDA_A0h_User_wait_flag = 0xA0,
  BDA_A8h_video_param_ctrl_block_Offset = 0xA8,
  BDA_AAh_video_param_ctrl_block_Segment = 0xAA,
  BDA_BFh_custom_semaphore = 0xBF,
};

/* 59 */
enum __bitmask __bin __lzero BDA_90h_drive0_media_state_flags : unsigned __int8
{
  drive_media_state_DOUBLE_STEP = 0b00100000,
  drive_media_state_ESTABLISHED = 0b00010000,
  drive_media_state_BIT3_RESERVED = 0b00001000,
};

/* 60 */
enum __bitmask __bin __lzero BDA_8Bh_floppy_cfg_data : unsigned __int8
{
  floppy_cfg_START_RATE_MASK = 0x0C,    ///< MASK
  floppy_cfg_START_RATE_500KBPS = 0b00000000,
  floppy_cfg_START_RATE_300KBPS = 0b00000100,
  floppy_cfg_START_RATE_250KBPS = 0b00001000,
  floppy_cfg_START_RATE_1MBPS = 0b00001100,
  floppy_cfg_LAST_STEP_RATE_MASK = 0x30, ///< MASK
  floppy_cfg_LAST_STEP_RATE_8ms = 0b00000000,
  floppy_cfg_LAST_STEP_RATE_7ms = 0b00010000,
  floppy_cfg_LAST_STEP_RATE_6ms = 0b00100000,
  floppy_cfg_LAST_STEP_RATE_5ms = 0b00110000,
  floppy_cfg_LAST_RATE_MASK = 0xC0,     ///< MASK
  floppy_cfg_LAST_RATE_500KBPS = 0b00000000,
  floppy_cfg_LAST_RATE_300KBPS = 0b01000000,
  floppy_cfg_LAST_RATE_250KBPS = 0b10000000,
  floppy_cfg_LAST_RATE_1MBPS = 0b11000000,
};

/* 61 */
enum __bitmask __bin __lzero BDA_floppy_cfg_START_RATE : unsigned __int8
{
  START_RATE_MASK_ = 0x0C,              ///< MASK
  START_RATE_500KBPS_ = 0b00000000,
  START_RATE_300KBPS_ = 0b00000100,
  START_RATE_250KBPS_ = 0b00001000,
  START_RATE_1MBPS_ = 0b00001100,
};

/* 62 */
enum __bitmask __bin __lzero BDA_floppy_cfg_LAST_RATE : unsigned __int8
{
  LAST_RATE_MASK = 0xC0,                ///< MASK
  LAST_RATE_500KBPS = 0b00000000,
  LAST_RATE_300KBPS = 0b01000000,
  LAST_RATE_250KBPS = 0b10000000,
  LAST_RATE_1MBPS = 0b11000000,
};

/* 63 */
enum __bitmask __bin __lzero BDA_3Fh_floppy_motor_status : unsigned __int8
{
  motor_status_drive0_ON = 0b00000001,
  motor_status_drive1_ON = 0b00000010,
  motor_status_drive2_ON = 0b00000100,
  motor_status_drive3_ON = 0b00001000,
  motor_status_drive_select_MASK = 0x30, ///< MASK 0 status_selected_0
  motor_status_selected_1 = 0b00010000,
  motor_status_selected_2 = 0b00100000,
  motor_status_selected_3 = 0b00110000,
  motor_status_unused = 0b01000000,
  motor_status_WRITE = 0b10000000,      ///< MASK bit7 0 READ
};

/* 64 */
enum int13h_services : unsigned __int16
{
  int13h_0_Reset_disk_system = 0x0,
  int13h_1_Get_disk_status = 0x1,
  int13h_2_Read_disk_sectors = 0x2,
  int13h_201_Read_one_disk_sector = 0x201,
  int13h_3_Write_disk_sectors = 0x3,
  int13h_4_Verify_disk_sectors = 0x4,
  int13h_401_Verify_1_sector = 0x401,
  int13h_5_Format_disk_track = 0x5,
  int13h_6_Format_track_and_set_bad_sector_flag = 0x6,
  int13h_7_Format_the_drive_starting_at_track = 0x7,
  int13h_8_Get_current_drive_parameters = 0x8,
  int13h_801_Get_current_drive_parameters = 0x801,
  int13h_9_Initialize_Fixed_Disk_Table = 0x9,
  int13h_901_Initialize_Fixed_Disk_Table = 0x901,
  int13h_A_Read_long_sector = 0xA,
  int13h_B_Write_long_sector = 0xB,
  int13h_C_Seek_to_cylinder = 0xC,
  int13h_D_Alternate_disk_reset = 0xD,
  int13h_D01_Alternate_disk_reset = 0xD01,
  int13h_E_Read_sector_buffer = 0xE,
  int13h_F_Write_sector_buffer = 0xF,
  int13h_10_Test_for_drive_ready = 0x10,
  int13h_1001_Test_for_drive_ready = 0x1001,
  int13h_11_Recalibrate_drive = 0x11,
  int13h_1101_Recalibrate_drive = 0x1101,
  int13h_12_Controller_ram_diagnostic = 0x12,
  int13h_13_Drive_diagnostic = 0x13,
  int13h_14_Controller_internal_diagnostic = 0x14,
  int13h_1400_Controller_internal_diagnostic = 0x1400,
  int13h_15_Read_disk_type = 0x15,
  int13h_16_Disk_change_line_status = 0x16,
  int13h_17_Set_dasd_type_for_format = 0x17,
  int13h_18_Set_media_type_for_format = 0x18,
  int13h_1800_Set_media_type_for_format = 0x1800,
  int13h_19_Park_fixed_disk_heads = 0x19,
  int13h_1A_Format_ESDI_drive_unit = 0x1A,
  int13h_Floppy0 = 0x0,
  int13h_Floppy1 = 0x1,
  int13h_Floppy2 = 0x2,
  int13h_Floppy3 = 0x3,
  int13h_HDD0_80h = 0x80,
  int13h_HDD1_81h = 0x81,
};

/* 120 */
enum __bitmask __bin __lzero BDA_90h_drive0_media_state : unsigned __int8
{
  FLOPPY_STATE_RATE_MASK = 0xC0,        ///< MASK 0 = 500KBPS
  FLOPPY_STATE_RATE_300KBPS = 0b01000000,
  FLOPPY_STATE_RATE_250KBPS = 0b10000000,
  FLOPPY_STATE_double_stepping = 0b00100000,
  FLOPPY_STATE_known_media = 0b00010000,
  FLOPPY_STATE_BIT3_RESERVED = 0b00001000,
  FLOPPY_STATE_MASK = 0x07,             ///< MASK 0 = TRY_360K_IN_360K
  FLOPPY_STATE_TRY_360K_IN_1_2MB = 0b00000001,
  FLOPPY_STATE_TRY_1_2MB_IN_1_2MB = 0b00000010,
  FLOPPY_STATE_EST_360K_IN_360K = 0b00000011,
  FLOPPY_STATE_EST_360K_IN_1_2MB = 0b00000100,
  FLOPPY_STATE_EST_1_2MB_IN_1_2MB = 0b00000101,
  FLOPPY_STATE_RESERVED = 0b00000110,
  FLOPPY_STATE_OTHER_FORMATS = 0b00000111,
};

/* 65 */
typedef BDA_90h_drive0_media_state BDA_91h_drive1_media_state;

/* 67 */
enum __bitmask __bin __lzero BDA_41h_floppy_status : unsigned __int8
{
  FDC_status_NOT_READY = 0b10000000,
  FDC_status_SEEK_ERROR = 0b01000000,
  FDC_status_CTRL_FAIL = 0b00100000,
  FDC_status_error_MASK = 0x1F,         ///< MASK
  FDC_status_no_errors = 0b00000000,
  FDC_status_bad_command = 0b00000001,
  FDC_status_address_mark_not_found = 0b00000010,
  FDC_status_write_protected = 0b00000011,
  FDC_status_sector_not_found = 0b00000100,
  FDC_status_disk_change_line_active = 0b00000110,
  FDC_status_DMA_overrun = 0b00001000,
  FDC_status_DMA_boundary_error = 0b00001001,
  FDC_status_unknown_invalid_media_type = 0b00001100,
  FDC_status_CRC_error_on_read = 0b00010000,
};

/* 68 */
enum __bitmask __bin __lzero BDA_10h_equipment_list : unsigned __int16
{
  EQ_BOOT_FLOPPY = 0b0000000000000001,
  EQ_COPROCESSOR = 0b0000000000000010,
  EQ_PS2_MOUSE = 0b0000000000000100,
  EQ_reserved = 0b0000000000001000,
  EQ_VIDEO_MASK = 0x0030,               ///< MASK 0 = EQ_VIDEO_EGA_VGA
  EQ_VIDEO_CGA_40X25 = 0b0000000000010000,
  EQ_VIDEO_CGA_80X25 = 0b0000000000100000,
  EQ_VIDEO_MONO_80X25 = 0b0000000000110000,
  EQ_FLOPPY_COUNT_MASK = 0x00C0,        ///< MASK 0 = EQ_FLOPPY_1
  EQ_FLOPPY_2 = 0b0000000001000000,
  EQ_FLOPPY_3 = 0b0000000010000000,
  EQ_FLOPPY_4 = 0b0000000011000000,
  EQ_reserved2 = 0b0000000100000000,
  EQ_COM_MASK = 0x0E00,                 ///< MASK 0 = EQ_COM_0
  EQ_COM_1 = 0b0000001000000000,
  EQ_COM_2 = 0b0000010000000000,
  EQ_COM_3 = 0b0000011000000000,
  EQ_COM_4 = 0b0000100000000000,
  EQ_GAME_PORT = 0b0001000000000000,
  EQ_INTERNAL_MODEM = 0b0010000000000000,
  EQ_LPT_MASK = 0xC000,                 ///< MASK 0 = EQ_LPT_0
  EQ_LPT_1 = 0b0100000000000000,
  EQ_LPT_2 = 0b1000000000000000,
  EQ_LPT_3 = 0b1100000000000000,
};

/* 69 */
enum __bitmask __bin __lzero IO_Port_0Bh_DMA1_Mode : unsigned __int8
{
  IO_Port_0Bh_DMA1_Mode_CH_MASK = 0x03, ///< MASK
  IO_Port_0Bh_DMA1_Mode_CH0 = 0b00000000,
  IO_Port_0Bh_DMA1_Mode_CH1 = 0b00000001,
  IO_Port_0Bh_DMA1_Mode_CH2 = 0b00000010,
  IO_Port_0Bh_DMA1_Mode_CH3 = 0b00000011,
  IO_Port_0Bh_DMA1_Mode_TYPE_MASK = 0x0C, ///< MASK
  IO_Port_0Bh_DMA1_Mode_TYPE_Verify = 0b00000000,
  IO_Port_0Bh_DMA1_Mode_TYPE_Write = 0b00000100,
  IO_Port_0Bh_DMA1_Mode_TYPE_Read = 0b00001000,
  IO_Port_0Bh_DMA1_Mode_TYPE_INVALID = 0b00001100,
  IO_Port_0Bh_DMA1_Mode_AUTO_Init = 0b00010000,
  IO_Port_0Bh_DMA1_Mode_ADDR_Dec = 0b00100000,
  IO_Port_0Bh_DMA1_Mode_MASK = 0xC0,    ///< MASK
  IO_Port_0Bh_DMA1_Mode_Demand = 0b00000000,
  IO_Port_0Bh_DMA1_Mode_Single = 0b01000000,
  IO_Port_0Bh_DMA1_Mode_Block = 0b10000000,
  IO_Port_0Bh_DMA1_Mode_Cascade = 0b11000000,
};

/* 70 */
enum __bitmask __bin __lzero CMOS_10h_Floppy_Drive_Type : unsigned __int8
{
  CMOS_10h_FDD1_type_MASK = 0x0F,       ///< MASK 0 = FDD1_type_no_drive
  CMOS_10h_FDD1_type_360KB_5_25 = 0b00000001,
  CMOS_10h_FDD1_type_1_2MB_5_25 = 0b00000010,
  CMOS_10h_FDD1_type_720KB_3_5 = 0b00000011,
  CMOS_10h_FDD1_type_1_44MB_3_5 = 0b00000100,
  CMOS_10h_FDD1_type_2_88MB_3_5 = 0b00000101,
  CMOS_10h_FDD0_type_MASK = 0xF0,       ///< MASK 0 = FDD0_type_no_drive
  CMOS_10h_FDD0_type_360KB_5_25 = 0b00010000,
  CMOS_10h_FDD0_type_1_2MB_5_25 = 0b00100000,
  CMOS_10h_FDD0_type_720KB_3_5 = 0b00110000,
  CMOS_10h_FDD0_type_1_44MB_3_5 = 0b01000000,
  CMOS_10h_FDD0_type_2_88MB_3_5 = 0b01010000,
};

/* 71 */
enum __bitmask __bin __lzero BDA_44h_floppy_status_register_ST2 : unsigned __int8
{
  FDC_ST2_MISSING_ADDRESS_MARK_DATA = 0b00000001,
  FDC_ST2_BAD_CYLINDER = 0b00000010,
  FDC_ST2_SCAN_NOT_SATISFIED = 0b00000100,
  FDC_ST2_SCAN_EQUAL_HIT = 0b00001000,
  FDC_ST2_WRONG_CYLINDER = 0b00010000,
  FDC_ST2_CRC_ERROR_DATA_FIELD = 0b00100000,
  FDC_ST2_CONTROL_MARK = 0b01000000,
};

/* 77 */
enum __bitmask __bin __lzero IO_Port_3F4h_FDD_Main_Status : unsigned __int8
{
  IO_Port_3F4h_FDC_MSR_DRV_BUSY_MASK = 0x0F, ///< MASK
  IO_Port_3F4h_FDC_MSR_DRV0_BUSY = 0b00000001,
  IO_Port_3F4h_FDC_MSR_DRV1_BUSY = 0b00000010,
  IO_Port_3F4h_FDC_MSR_DRV2_BUSY = 0b00000100,
  IO_Port_3F4h_FDC_MSR_DRV3_BUSY = 0b00001000,
  IO_Port_3F4h_FDC_MSR_BUSY = 0b00010000,
  IO_Port_3F4h_FDC_MSR_NON_DMA_MODE = 0b00100000,
  IO_Port_3F4h_FDC_MSR_DIO_CNTRLR_TO_CPU = 0b01000000, ///< bit6 0 = MSR_DIO_CPU_TO_CNTRLR
  IO_Port_3F4h_FDC_MSR_RQM_READY = 0b10000000,
};

/* 78 */
enum __bitmask __bin __lzero BDA_3Eh_floppy_calibration_status : unsigned __int8
{
  RECALIBRATE_INT_OCCURRED_MASK = 0x80, ///< MASK
  RECALIBRATE_INT_PENDING = 0b00000000,
  RECALIBRATE_INT_COMPLETE = 0b10000000,
  RECALIBRATE_DRV_MASK = 0x0F,          ///< MASK
  RECALIBRATE_DRV0 = 0b00000001,
  RECALIBRATE_DRV1 = 0b00000010,
  RECALIBRATE_DRV2 = 0b00000100,
  RECALIBRATE_DRV3 = 0b00001000,
};

/* 79 */
enum __bitmask __bin __lzero BDA_6Bh_last_irq : unsigned __int8
{
  last_irq7_DID_OCCUR = 0b10000000,
  last_irq6_DID_OCCUR = 0b01000000,
  last_irq5_DID_OCCUR = 0b00100000,
  last_irq4_DID_OCCUR = 0b00010000,
  last_irq3_DID_OCCUR = 0b00001000,
  last_irq2_DID_OCCUR = 0b00000100,
  last_irq1_DID_OCCUR = 0b00000010,
  last_irq0_DID_OCCUR = 0b00000001,
};

/* 80 */
enum BDA_72h_soft_reset_flag : unsigned __int16
{
  soft_reset_WARM_BOOT = 0x1234,
  soft_reset_PRESERVE_MEM = 0x4321,
  soft_reset_SUSPEND = 0x5678,
  soft_reset_MFG_TEST = 0x9ABC,
  soft_reset_CONV_POST = 0xABCD,
};

/* 81 */
enum BDA_74h_HDD_last_op_status : unsigned __int8
{
  BDA_74h_status_0_OK = 0x0,
  BDA_74h_status_1_INVALID_FUNC = 0x1,
  BDA_74h_status_2_ADDR_MARK_NOT_FND = 0x2,
  BDA_74h_status_3_WRITE_PROTECT = 0x3,
  BDA_74h_status_4_SECTOR_NOT_FND = 0x4,
  BDA_74h_status_5_RESET_FAILED = 0x5,
  BDA_74h_status_6_Disk_changed_removed = 0x6,
  BDA_74h_status_7_Paameter_Table_ERR = 0x7,
  BDA_74h_status_8_DMA_OVERRUN = 0x8,
  BDA_74h_status_9_DMA_64K_Boundary_ERR = 0x9,
  BDA_74h_status_A_BAD_SECTOR_FLAG = 0xA,
  BDA_74h_status_B_BAD_TRACK = 0xB,
  BDA_74h_status_D_FORMAT_INVALID_SEC = 0xD,
  BDA_74h_status_E_CTRL_ADDR_MARK = 0xE,
  BDA_74h_status_F_DMA_ARB_LEVEL_ERR = 0xF,
  BDA_74h_status_10_UNCORRECTABLE_ECC = 0x10,
  BDA_74h_status_11_ECC_CORRECTED = 0x11,
  BDA_74h_status_20_CONTROLLER_FAILURE = 0x20,
  BDA_74h_status_40_SEEK_FAILED = 0x40,
  BDA_74h_status_80_TIMEOUT = 0x80,
  BDA_74h_status_AA_DRIVE_NOT_READY = 0xAA,
  BDA_74h_status_BB_UNDEFINED_ERROR = 0xBB,
  BDA_74h_status_CC_WRITE_FAULT = 0xCC,
  BDA_74h_status_E0_STATUS_ERROR = 0xE0,
  BDA_74h_status_FF_SENSE_FAILED = 0xFF,
};

/* 82 */
enum BDA_75h_HDD_count : unsigned __int8
{
  HDD_count_NONE = 0x0,
  HDD_count_1 = 0x1,
  HDD_count_2 = 0x2,
};

/* 84 */
struct text_mode_params
{
  unsigned __int8 num_pages;
  unsigned __int16 page_size;
  unsigned __int16 columns __udec;
  unsigned __int16 crtc_port;
  unsigned __int16 mode_reg;
  unsigned __int8 palette;
};

/* 85 */
enum BDA_49h_video_active_mode : unsigned __int8
{
  VIDEO_MODE_40x25_BW_TEXT = 0x0,
  VIDEO_MODE_40x25_Color_TEXT = 0x1,
  VIDEO_MODE_80x25_BW_TEXT = 0x2,
  VIDEO_MODE_80x25_Color_TEXT = 0x3,
  VIDEO_MODE_320x200_Color_GRA = 0x4,
  VIDEO_MODE_320x200_BW_GRA = 0x5,
  VIDEO_MODE_640x200_BW_GRA = 0x6,
  VIDEO_MODE_80x25_MDA_TEXT = 0x7,
  VIDEO_MODE_160x200_Color_PCJR = 0x8,
  VIDEO_MODE_320x200_Color_PCJR = 0x9,
  VIDEO_MODE_640x200_Color_PCJR = 0xA,
  VIDEO_MODE_RESERVED_0B = 0xB,
  VIDEO_MODE_RESERVED_0C = 0xC,
  VIDEO_MODE_320x200_Color_EGA = 0xD,
  VIDEO_MODE_640x200_Color_EGA = 0xE,
  VIDEO_MODE_640x350_MONO_EGA = 0xF,
  VIDEO_MODE_640x350_Color_EGA = 0x10,
  VIDEO_MODE_640x480_BW_VGA = 0x11,
  VIDEO_MODE_640x480_Color_VGA = 0x12,
  VIDEO_MODE_320x200_256_Color_VGA = 0x13,
  VIDEO_MODE_NO_CLEAR_MEM = 0x80,
};

/* 86 */
enum int10h_services : unsigned __int8
{
  int10h_0_Set_video_mode = 0x0,
  int10h_1_Set_cursor_type = 0x1,
  int10h_2_Set_cursor_position = 0x2,
  int10h_3_Read_cursor_position = 0x3,
  int10h_4_Read_light_pen = 0x4,
  int10h_5_Select_active_display_page = 0x5,
  int10h_6_Scroll_active_page_up = 0x6,
  int10h_7_Scroll_active_page_down = 0x7,
  int10h_8_Read_character_and_attribute_at_cursor = 0x8,
  int10h_9_Write_character_and_attribute_at_cursor = 0x9,
  int10h_A_Write_character_at_current_cursor = 0xA,
  int10h_B_Set_color_palette = 0xB,
  int10h_C_Write_graphics_pixel_at_coordinate = 0xC,
  int10h_D_Read_graphics_pixel_at_coordinate = 0xD,
  int10h_E_Write_text_in_teletype_mode = 0xE,
  int10h_0E0A_Write_LineFeed_in_teletype_mode = 0xA,
  int10h_F_Get_current_video_state = 0xF,
  int10h_10_Set_palette_registers = 0x10,
  int10h_11_Character_generator_routine = 0x11,
  int10h_12_Video_subsystem_configuration = 0x12,
  int10h_13_Write_string = 0x13,
  int10h_14_Load_LCD_char_font = 0x14,
  int10h_15_Return_physical_display_parms = 0x15,
  int10h_1A_Video_Display_Combination = 0x1A,
  int10h_1B_Video_BIOS_State_Information = 0x1B,
  int10h_1C_Save_Restore_Video_State = 0x1C,
  int10h_FE_Get_DESQView_Virtual_Screen_Buffer = 0xFE,
  int10h_FF_Update_DESQView_Virtual_Screen_Buffer = 0xFF,
};

/* 87 */
enum __bitmask __bin __lzero BDA_76h_HDD_ctrl_byte : unsigned __int8
{
  HDD_ctrl_disk1_RETRY_DISABLE = 0b10000000,
  HDD_ctrl_disk0_RETRY_DISABLE = 0b01000000,
  HDD_ctrl_HEADS_MORE_THAN_8 = 0b00001000, ///< HDD_ctrl_HEADS_LESS_THAN_8 = 0b00000000
};

/* 89 */
enum __bitmask IO_Port_70h_CMOS_Index : unsigned __int8
{
  CMOS_MASK = 0x7F,                     ///< MASK
  CMOS_00h_RTC_seconds = 0x0,
  CMOS_01h_RTC_seconds_alarm = 0x1,
  CMOS_02h_RTC_minutes = 0x2,
  CMOS_03h_RTC_minutes_alarm = 0x3,
  CMOS_04h_RTC_hours = 0x4,
  CMOS_05h_RTC_hours_alarm = 0x5,
  CMOS_06h_RTC_day_of_week = 0x6,
  CMOS_07h_RTC_day_of_month = 0x7,
  CMOS_08h_RTC_month = 0x8,
  CMOS_09h_RTC_year = 0x9,
  CMOS_0Ah_Status_Register_A = 0xA,
  CMOS_0Bh_Status_Register_B = 0xB,
  CMOS_0Ch_Status_Register_C = 0xC,
  CMOS_0Dh_Status_Register_D = 0xD,
  CMOS_0Eh_Diagnostic_Status = 0xE,
  CMOS_0Fh_Shutdown_Status = 0xF,
  CMOS_10h_Floppy_Drive_Type = 0x10,
  CMOS_11h_Reserved = 0x11,
  CMOS_12h_HDD_Type = 0x12,
  CMOS_13h_Reserved = 0x13,
  CMOS_14h_Equipment_Byte = 0x14,
  CMOS_15h_Base_Memory_Low = 0x15,
  CMOS_16h_Base_Memory_High = 0x16,
  CMOS_15h_Zenith_Base_Fill_64K_Blocks_Low = 0x15,
  CMOS_16h_Zenith_Base_Fill_64K_Blocks_High = 0x16,
  CMOS_17h_Expansion_Memory_Low = 0x17,
  CMOS_18h_Expansion_Memory_High = 0x18,
  CMOS_19h_HDD_0_Extended = 0x19,
  CMOS_1Ah_HDD_1_Extended = 0x1A,
  CMOS_1Ch_Award_checksum = 0x1C,
  CMOS_1Dh_Zenith_Turbo = 0x1D,
  CMOS_1Eh_Zenith_COM_LPT = 0x1E,
  CMOS_1Fh_Zenith_ram_base_ext = 0x1F,
  CMOS_20h_Zenith_ram_total_MB = 0x20,
  CMOS_21h_Zenith_Cache = 0x21,
  CMOS_22h_Zenith_custom_something = 0x22,
  CMOS_23h_Zenith_custom_something = 0x23,
  CMOS_24h_Zenith_custom_something = 0x24,
  CMOS_25h_Zenith_custom_something = 0x25,
  CMOS_26h_Zenith_custom_something = 0x26,
  CMOS_27h_Zenith_custom_something = 0x27,
  CMOS_28h_Zenith_custom_something = 0x28,
  CMOS_29h_Zenith_custom_something = 0x29,
  CMOS_2Ah_Zenith_custom_something = 0x2A,
  CMOS_2Bh_Zenith_custom_something = 0x2B,
  CMOS_2Ch_Zenith_custom_something = 0x2C,
  CMOS_2Dh_Zenith_custom_something = 0x2D,
  CMOS_2Eh_Checksum_High = 0x2E,
  CMOS_2Fh_Checksum_Low = 0x2F,
  CMOS_30h_Expansion_Memory_Above_1MB_Low = 0x30,
  CMOS_31h_Expansion_Memory_Above_1MB_High = 0x31,
  CMOS_32h_Century_Byte = 0x32,
  CMOS_33h_Information_Flags = 0x33,
  CMOS_34h_Zenith_ram_total_256KB_Units = 0x34,
  CMOS_35h_Zenith_Password_enabled = 0x35,
  CMOS_NMI_flag = 0x80,
};

/* 90 */
enum __bitmask __bin __lzero CMOS_0Eh_Diagnostic_Status : unsigned __int8
{
  CMOS_0Eh_CMOS_Diag_RTC_POWER_LOST = 0b10000000,
  CMOS_0Eh_CMOS_Diag_CHECKSUM_BAD = 0b01000000,
  CMOS_0Eh_CMOS_Diag_CONFIG_INVALID = 0b00100000,
  CMOS_0Eh_CMOS_Diag_MEM_SIZE_MISMATCH = 0b00010000,
  CMOS_0Eh_CMOS_Diag_HDD_INIT_FAILED = 0b00001000,
  CMOS_0Eh_CMOS_Diag_TIME_INVALID = 0b00000100,
  CMOS_0Eh_CMOS_Diag_RESERVED_BIT1 = 0b00000010,
  CMOS_0Eh_CMOS_Diag_RESERVED_BIT0 = 0b00000001,
};

/* 91 */
enum __bitmask __bin __lzero CMOS_14h_Equipment_Byte : unsigned __int8
{
  CMOS_14h_Equip_FLOPPY_COUNT_MASK = 0b11000000,
  CMOS_14h_Equip_DISPLAY_TYPE_MASK = 0b00110000,
  CMOS_14h_Equip_DISPLAY_INSTALLED = 0b00001000,
  CMOS_14h_Equip_KEYBOARD_INSTALLED = 0b00000100,
  CMOS_14h_Equip_MATH_COPRO_INST = 0b00000010,
  CMOS_14h_Equip_ALWAYS_SET = 0b00000001,
};

/* 92 */
enum IO_Port_72h_FE3001_Command_Index : unsigned __int8
{
  FE3031_0_BALE_delay = 0x0,
  FE3031_1_BALE_width = 0x4,
  FE3031_3_8bit_mem_16bit_IO_cmd_delay = 0xC,
  FE3031_4_8bit_waitstates = 0x40,
  FE3031_5_16bit_IO_waitstates = 0x44,
  FE3031_6_16bit_mem_command_delay = 0x48,
  FE3031_7_16bit_mem_waitstates = 0x4C,
  FE3031_8_16bit_mem_waitstates = 0x80,
  FE3031_9_local_DRAM_read_waitstates = 0x84,
  FE3031_10_local_DRAM_write_waitstates = 0x88,
  FE3031_11_local_DRAM_read_delay = 0x8C,
  FE3031_12_onboard_IO_delay = 0xC0,
};

/* 93 */
enum IO_Port_73h_FE3001_Command_Data : __int8
{
  FE3031_DATA_0h = 0x0,
  FE3031_DATA_1h = 0x4,
  FE3031_DATA_2h = 0x8,
  FE3031_DATA_3h = 0xC,
  FE3031_DATA_4h = 0x40,
  FE3031_DATA_5h = 0x44,
  FE3031_DATA_6h = 0x48,
  FE3031_DATA_7h = 0x4C,
  FE3031_DATA_8h = 0x80,
  FE3031_DATA_9h = 0x84,
  FE3031_DATA_Ah = 0x88,
  FE3031_DATA_Bh = 0x8C,
  FE3031_DATA_Ch = 0xC0,
  FE3031_DATA_Dh = 0xC4,
  FE3031_DATA_Eh = 0xC8,
  FE3031_DATA_Fh = 0xCC,
};

/* 95 */
#pragma pack(push, 1)
struct FE3001_reg_pair
{
  IO_Port_72h_FE3001_Command_Index index;
  IO_Port_73h_FE3001_Command_Data data;
};
#pragma pack(pop)

/* 94 */
#pragma pack(push, 1)
struct FE3001_init
{
  __int16 len;
  FE3001_reg_pair byte[];
};
#pragma pack(pop)

/* 96 */
enum __lzero CMOS_0Fh_Shutdown_Status : unsigned __int8
{
  CMOS_0Fh_Shutdown_NORMAL = 0x00,
  CMOS_0Fh_Shutdown_MEM_SIZE_PASS = 0x01,
  CMOS_0Fh_Shutdown_MEM_TEST_PASS = 0x02,
  CMOS_0Fh_Shutdown_MEM_TEST_FAIL = 0x03,
  CMOS_0Fh_Shutdown_BOOT_SYSTEM = 0x04,
  CMOS_0Fh_Shutdown_JMP_DWORD_EOI = 0x05,
  CMOS_0Fh_Shutdown_PROT_MODE_PASS = 0x06,
  CMOS_0Fh_Shutdown_PROT_MODE_FAIL = 0x07,
  CMOS_0Fh_Shutdown_MEM_SIZE_FAIL = 0x08,
  CMOS_0Fh_Shutdown_INT15_BLOCK_MOVE = 0x09,
  CMOS_0Fh_Shutdown_JMP_DWORD_NO_EOI = 0x0A,
  CMOS_0Fh_Shutdown_USED_BY_80386 = 0x0B,
  CMOS_11h_Shutdown_Zenith_SCP_failure = 0x11,
};

/* 97 */
struct IDT_Gate
{
  unsigned __int16 offset_low __offset(OFF16|AUTO);
  unsigned __int16 selector;
  unsigned __int8 zero;
  unsigned __int8 access;
  unsigned __int16 offset_high;
};

/* 98 */
enum __bitmask __bin __lzero CMOS_0Bh_Status_Register_B : unsigned __int8
{
  CMOS_0Bh_REGB_UPDATE_DISABLED = 0b10000000,
  CMOS_0Bh_REGB_PERIODIC_INT_EN = 0b01000000,
  CMOS_0Bh_REGB_ALARM_INT_EN = 0b00100000,
  CMOS_0Bh_REGB_UPDATE_INT_EN = 0b00010000,
  CMOS_0Bh_REGB_SQUARE_WAVE_EN = 0b00001000,
  CMOS_0Bh_REGB_DATA_MODE_BIN = 0b00000100,
  CMOS_0Bh_REGB_24_HOUR_MODE = 0b00000010,
  CMOS_0Bh_REGB_DAYLIGHT_SAV_EN = 0b00000001,
};

/* 99 */
enum __bitmask __bin __lzero BDA_A0h_User_Wait_Flag : unsigned __int8
{
  BDA_A0h_User_Wait_TIME_ELAPSED = 0b10000000,
  BDA_A0h_User_Wait_IN_PROGRESS = 0b00000001,
};

/* 100 */
enum __bitmask __bin CMOS_0Dh_Status_Register_D : __int8
{
  CMOS_0Dh_REGD_Battery_Good = 0b10000000,
};

/* 101 */
enum __bitmask __bin __lzero CMOS_0Ch_Status_Register_C : unsigned __int8
{
  CMOS_0Ch_REGC_IRQF_flag = 0b10000000,
  CMOS_0Ch_REGC_PF_flag = 0b01000000,
  CMOS_0Ch_REGC_AF_flag = 0b00100000,
  CMOS_0Ch_REGC_UF_flag = 0b00010000,
};

/* 102 */
enum __bitmask __bin __lzero CMOS_0Ah_Status_Register_A : unsigned __int8
{
  CMOS_0Ah_REGA_time_update_in_progress = 0b10000000,
  CMOS_0Ah_REGA_timebase_32_768Khz = 0b00100000,
  CMOS_0Ah_REGA_rate_MASK = 0x0F,       ///< MASK
  CMOS_0Ah_REGA_rate_1024Hz = 0b00000110,
};

/* 187 */
enum ZBIOS_Record_Type : __int8
{
  ZBIOS_Type_0_Radio = 0x0,
  ZBIOS_Type_1_List = 0x1,
  ZBIOS_Type_2_Input = 0x2,
  ZBIOS_Type_3_unknown = 0x3,
  ZBIOS_Type_4_Date = 0x4,
  ZBIOS_Type_5_Time = 0x5,
  ZBIOS_Type_max_count = 0x6,
};

/* 103 */
#pragma pack(push, 1)
struct ZBIOS_Record
{
  unsigned __int8 Row_Y __udec;
  unsigned __int8 Column_X __udec;
  ZBIOS_Record_Type Type;
  unsigned __int8 Up_target_idx __udec;
  unsigned __int8 Down_target_idx __udec;
  unsigned __int8 Right_target_idx __udec;
  unsigned __int8 Left_target_idx __udec;
  unsigned __int16 Default_value __udec;
  unsigned __int8 Label_idx __udec;
  unsigned __int8 Input_msg_idx __udec;
  unsigned __int8 Options_count __udec;
  unsigned __int8 unknown_byte;
  unsigned __int16 Handler_ptr __offset(OFF16|AUTO);
};
#pragma pack(pop)

/* 106 */
enum __bitmask __bin __lzero CMOS_12h_HDD_Type : unsigned __int8
{
  CMOS_12h_HDD1_MASK = 0x0F,            ///< MASK
  CMOS_12h_HDD1_Type_1 = 0b00000001,
  CMOS_12h_HDD1_Type_14 = 0b00001110,
  CMOS_12h_HDD1_Type_16_47_defined_in_19h = 0b00001111,
  CMOS_12h_HDD0_MASK = 0xF0,            ///< MASK
  CMOS_12h_HDD0_Type_1 = 0b00010000,
  CMOS_12h_HDD0_Type_14 = 0b11100000,
  CMOS_12h_HDD0_Type_16_47_defined_in_19h = 0b11110000,
};

/* 107 */
enum __bitmask __bin __lzero IO_Port_A1h_PIC2_Interrupt_Mask : unsigned __int8
{
  IO_Port_A1h_PIC2_I_IRQ15_RESERVED = 0b10000000,
  IO_Port_A1h_PIC2_I_IRQ14_PRIMARY_IDE = 0b01000000,
  IO_Port_A1h_PIC2_I_IRQ13_COPROCESSOR = 0b00100000,
  IO_Port_A1h_PIC2_I_IRQ12_PS2_MOUSE = 0b00010000,
  IO_Port_A1h_PIC2_I_IRQ11_RESERVED = 0b00001000,
  IO_Port_A1h_PIC2_I_IRQ10_RESERVED = 0b00000100,
  IO_Port_A1h_PIC2_I_IRQ9_REDIRECT_IRQ2 = 0b00000010,
  IO_Port_A1h_PIC2_I_IRQ8_REAL_TIME_CLOCK = 0b00000001,
};

/* 109 */
enum __bitmask __bin __lzero IO_Port_21h_PIC1_Interrupt_Mask : unsigned __int8
{
  IO_Port_21h_PIC1_I_IRQ7_LPT1 = 0b10000000,
  IO_Port_21h_PIC1_I_IRQ6_FLOPPY = 0b01000000,
  IO_Port_21h_PIC1_I_IRQ5_LPT2_SOUND = 0b00100000,
  IO_Port_21h_PIC1_I_IRQ4_COM1 = 0b00010000,
  IO_Port_21h_PIC1_I_IRQ3_COM2 = 0b00001000,
  IO_Port_21h_PIC1_I_IRQ2_CASCADE = 0b00000100,
  IO_Port_21h_PIC1_I_IRQ1_KEYBOARD = 0b00000010,
  IO_Port_21h_PIC1_I_IRQ0_TIMER = 0b00000001,
};

/* 123 */
enum __bin __lzero IO_Port_A0h_PIC2_Command : unsigned __int8
{
  IO_Port_PIC_Cmd_INIT_CASCADE_ICW4 = 0b00010001,
  IO_Port_PIC_Cmd_INIT_SINGLE_ICW4 = 0b00010011,
  IO_Port_PIC_Cmd_MODE_8086 = 0b00000001,
  IO_Port_PIC_Cmd_MODE_8086_AEOI = 0b00000011,
  IO_Port_PIC_Cmd_NON_SPECIFIC_EOI = 0b00100000,
  IO_Port_PIC_Cmd_SPECIFIC_EOI_IRQ0 = 0b01100000,
  IO_Port_PIC_Cmd_SPECIFIC_EOI_IRQ1 = 0b01100001,
  IO_Port_PIC_Cmd_SPECIFIC_EOI_IRQ2 = 0b01100010,
  IO_Port_PIC_Cmd_SPECIFIC_EOI_IRQ3 = 0b01100011,
  IO_Port_PIC_Cmd_SPECIFIC_EOI_IRQ4 = 0b01100100,
  IO_Port_PIC_Cmd_SPECIFIC_EOI_IRQ5 = 0b01100101,
  IO_Port_PIC_Cmd_SPECIFIC_EOI_IRQ6 = 0b01100110,
  IO_Port_PIC_Cmd_SPECIFIC_EOI_IRQ7 = 0b01100111,
  IO_Port_PIC_Cmd_READ_IRR = 0b00001010,
  IO_Port_PIC_Cmd_READ_ISR = 0b00001011,
  IO_Port_PIC_Cmd_POLL_MODE = 0b00001100,
};

/* 110 */
typedef IO_Port_A0h_PIC2_Command IO_Port_20h_PIC1_Command;

/* 111 */
enum __bitmask __bin __lzero BDA_8Ch_HDD_CTRL_status : unsigned __int8
{
  HDD_CTRL_BUSY = 0b10000000,           ///< Bit 7: 1 = controller busy, 0 = not busy
  HDD_CTRL_READY = 0b01000000,          ///< Bit 6: 1 = drive ready, 0 = not ready
  HDD_CTRL_WRITE_ERR = 0b00100000,      ///< Bit 5: 1 = write fault occurred
  HDD_CTRL_SEEK = 0b00010000,           ///< Bit 4: 1 = seek complete, 0 = drive seeking
  HDD_CTRL_DATA_REQ = 0b00001000,       ///< Bit 3: 1 = data request active
  HDD_CTRL_CORRECTED = 0b00000100,      ///< Bit 2: 1 = data corrected
  HDD_CTRL_INDEX = 0b00000010,          ///< Bit 1: 1 = index pulse active
  HDD_CTRL_ERROR = 0b00000001,          ///< Bit 0: 1 = error in previous command
};

/* 112 */
enum __bitmask __bin __lzero BDA_8Dh_HDD_ERROR_byte : unsigned __int8
{
  HDD_ERROR_BAD_SECTOR = 0b10000000,    ///< Bit 7: 1 = bad sector detected
  HDD_ERROR_ECC_ERROR = 0b01000000,     ///< Bit 6: 1 = uncorrectable ECC error occurred
  HDD_ERROR_MEDIA_CHANGE = 0b00100000,  ///< Bit 5: 1 = media changed
  HDD_ERROR_SECTOR_NOT_FOUND = 0b00010000, ///< Bit 4: 1 = ID or target sector not found
  HDD_ERROR_MEDIA_CHANGE_REQ = 0b00001000, ///< Bit 3: 1 = media change requested
  HDD_ERROR_CMD_ABORT = 0b00000100,     ///< Bit 2: 1 = command aborted
  HDD_ERROR_DRIVE_TRACK0 = 0b00000010,  ///< Bit 1: 1 = track 0 not found
  HDD_ERROR_ADDR_MARK = 0b00000001,     ///< Bit 0: 1 = address mark not found
};

/* 113 */
enum BDA_85h_scan_lines_per_char : unsigned __int16
{
  VIDEO_SCAN_LINES_8 = 0x8,
  VIDEO_SCAN_LINES_14 = 0xE,
  VIDEO_SCAN_LINES_16 = 0x10,
};

/* 114 */
enum __bitmask __bin __lzero BDA_87h_video_adapter_options : unsigned __int8
{
  VIDEO_OPT_CLEAR_BUFFER = 0b10000000,  ///< 0b = clear display buffer when setting mode, 1b = do not clear
  VIDEO_OPT_MEM_MASK = 0x70,            ///< MASK
  VIDEO_OPT_MEM_64K = 0b00000000,       ///< 64Kb
  VIDEO_OPT_MEM_128K = 0b00010000,      ///< 128Kb
  VIDEO_OPT_MEM_192K = 0b00100000,      ///< 192Kb
  VIDEO_OPT_MEM_256K = 0b00110000,      ///< 256Kb
  VIDEO_OPT_MEM_512K = 0b01000000,      ///< 512Kb
  VIDEO_OPT_MEM_1024K_PLUS = 0b01100000, ///< 1024Kb or more
  VIDEO_OPT_SUBSYS_ACTIVE = 0b00001000, ///< 1b = video subsystem active
  VIDEO_OPT_MONOCHROME = 0b00000010,    ///< 1b = monochrome monitor
  VIDEO_OPT_CURSOR_EMULATION = 0b00000001, ///< 1b = alphanumeric cursor emulation enabled
};

/* 115 */
enum __bitmask __bin __lzero BDA_88h_video_adapter_switches : unsigned __int8
{
  VIDEO_SW_type_MASK = 0x0F,            ///< MASK
  VIDEO_SW_MDA_40X25 = 0b00000000,
  VIDEO_SW_MDA_80X25 = 0b00000001,
  VIDEO_SW_MDA_HR_80X25 = 0b00000010,
  VIDEO_SW_MDA_HR_ENHANCED = 0b00000011,
  VIDEO_SW_CGA_40X25_MONO = 0b00000100,
  VIDEO_SW_CGA_80X25_MONO = 0b00000101,
  VIDEO_SW_COLOR_40X25_MDA = 0b00000110,
  VIDEO_SW_COLOR_80X25_MDA = 0b00000111,
  VIDEO_SW_HR_80X25_MDA = 0b00001000,
  VIDEO_SW_HR_ENHANCED_MDA = 0b00001001,
  VIDEO_SW_MONO_CGA_40X25 = 0b00001010,
  VIDEO_SW_MONO_CGA_80X25 = 0b00001011,
};

/* 116 */
enum __bitmask __bin __lzero BDA_89h_VGA_flags_1 : unsigned __int8
{
  VGA_flags1_SCANLINE_MASK = 0x90,      ///< MASK
  VGA_flags1_SCANLINE_350 = 0b00000000, ///< 350-line mode
  VGA_flags1_SCANLINE_400 = 0b00010000, ///< 400-line mode
  VGA_flags1_SCANLINE_200 = 0b10000000, ///< 200-line mode
  VGA_flags1_DISPLAY_SWITCH_ENABLED = 0b01000000, ///< 1b = enabled
  VGA_flags1_DEFAULT_PALETTE_LOADED = 0b00001000, ///< 1b = enabled
  VGA_flags1_MONOCHROME_MONITOR = 0b00000100, ///< 1b = monochrome
  VGA_flags1_GRAYSCALE_SUMMING = 0b00000010, ///< 1b = enabled
  VGA_flags1_VGA_ACTIVE = 0b00000001,   ///< 1b = VGA active
};

/* 117 */
enum __bitmask __bin __lzero BDA_7Bh_parallel_port4_timeout_vds : unsigned __int8
{
  VDS_SUPPORTED = 0b00100000,           ///< Bit 5: 1b = supported
  VDS_CHAIN_IRQ4B_REQUIRED = 0b00001000, ///< Bit 3: 1b = required
};

/* 119 */
enum __bitmask __bin __lzero BDA_93h_drive1_starting_state : unsigned __int8
{
  DRIVE_RATE_MASK = 0xC0,               ///< MASK
  DRIVE_RATE_500KBPS = 0b00000000,      ///< 500 Kbit/sec
  DRIVE_RATE_300KBPS = 0b01000000,      ///< 300 Kbit/sec
  DRIVE_RATE_250KBPS = 0b10000000,      ///< 250 Kbit/sec
  DRIVE_RATE_1MBPS = 0b11000000,        ///< 1 Mbit/sec
  DRIVE_DETERMINED = 0b00000100,        ///< 1b = drive type determined
  DRIVE_MULTIRATE = 0b00000010,         ///< 1b = drive is multirate
  DRIVE_CHANGE_line_detection = 0b00000001, ///< 1b = change line detection
};

/* 118 */
typedef BDA_93h_drive1_starting_state BDA_92h_drive0_starting_state;

/* 121 */
enum __bitmask __bin __lzero BDA_96h_keyboard_flags_3 : unsigned __int8
{
  BDA_96h_flags_3_READING_TWO_BYTE_ID = 0b10000000,
  BDA_96h_flags_3_LAST_CODE_FIRST_ID_CHAR = 0b01000000,
  BDA_96h_flags_3_FORCED_NumLock_ON = 0b00100000,
  BDA_96h_flags_3_NOT_101_102_Keyboard = 0b00010000,
  BDA_96h_flags_3_R_Alt_ACTIVE = 0b00001000,
  BDA_96h_flags_3_R_Ctrl_ACTIVE = 0b00000100,
  BDA_96h_flags_3_LAST_SCODE_E0 = 0b00000010,
  BDA_96h_flags_3_LAST_SCODE_E1 = 0b00000001,
};

/* 122 */
enum __bitmask __bin __lzero BDA_97h_keyboard_flags_4 : unsigned __int8
{
  BDA_97h_flags_4_TRANSMIT_ERROR = 0b10000000,
  BDA_97h_flags_4_LED_UPDATE_IN_PROGRESS = 0b01000000,
  BDA_97h_flags_4_RESEND_RECEIVED = 0b00100000,
  BDA_97h_flags_4_ACKNOWLEDGE_RECEIVED = 0b00010000,
  BDA_97h_flags_4_CapsLock_LED_ON = 0b00000100,
  BDA_97h_flags_4_NumLock_LED_ON = 0b00000010,
  BDA_97h_flags_4_ScrollLock_LED_ON = 0b00000001,
};

/* 195 */
enum BDA_48h_Zenith_IDE_1F7h_Command : unsigned __int8
{
  IDE_CMD_10_RECALIBRATE = 0x10,
  IDE_CMD_20_READ_SECTORS_RETRY = 0x20,
  IDE_CMD_21_READ_SECTORS = 0x21,
  IDE_CMD_22_READ_LONG_RETRY = 0x22,
  IDE_CMD_23_READ_LONG = 0x23,
  IDE_CMD_30_WRITE_SECTORS_RETRY = 0x30,
  IDE_CMD_31_WRITE_SECTORS = 0x31,
  IDE_CMD_32_WRITE_LONG_RETRY = 0x32,
  IDE_CMD_33_WRITE_LONG = 0x33,
  IDE_CMD_3C_WRITE_VERIFY = 0x3C,
  IDE_CMD_40_READ_VERIFY_RETRY = 0x40,
  IDE_CMD_41_READ_VERIFY = 0x41,
  IDE_CMD_50_FORMAT_TRACK = 0x50,
  IDE_CMD_70_SEEK = 0x70,
  IDE_CMD_80_VENDOR_UNIQUE_8X = 0x80,
  IDE_CMD_90_EXECUTE_DRIVE_DIAG = 0x90,
  IDE_CMD_91_INIT_DRIVE_PARAMS = 0x91,
  IDE_CMD_94_STANDBY_IMMEDIATE = 0x94,
  IDE_CMD_95_IDLE_IMMEDIATE = 0x95,
  IDE_CMD_96_STANDBY = 0x96,
  IDE_CMD_97_IDLE = 0x97,
  IDE_CMD_98_CHECK_POWER_MODE = 0x98,
  IDE_CMD_99_SET_SLEEP_MODE = 0x99,
  IDE_CMD_9A_VENDOR_UNIQUE = 0x9A,
  IDE_CMD_C0_VENDOR_UNIQUE = 0xC0,
  IDE_CMD_C1_VENDOR_UNIQUE = 0xC1,
  IDE_CMD_C2_VENDOR_UNIQUE = 0xC2,
  IDE_CMD_C3_VENDOR_UNIQUE = 0xC3,
  IDE_CMD_C4_READ_MULTIPLE = 0xC4,
  IDE_CMD_C5_WRITE_MULTIPLE = 0xC5,
  IDE_CMD_C6_SET_MULTIPLE_MODE = 0xC6,
  IDE_CMD_C8_READ_DMA_RETRY = 0xC8,
  IDE_CMD_C9_READ_DMA = 0xC9,
  IDE_CMD_CA_WRITE_DMA_RETRY = 0xCA,
  IDE_CMD_CB_WRITE_DMA = 0xCB,
  IDE_CMD_E0_STANDBY_IMMEDIATE = 0xE0,
  IDE_CMD_E1_IDLE_IMMEDIATE = 0xE1,
  IDE_CMD_E2_STANDBY = 0xE2,
  IDE_CMD_E3_IDLE = 0xE3,
  IDE_CMD_E4_READ_BUFFER = 0xE4,
  IDE_CMD_E5_CHECK_POWER_MODE = 0xE5,
  IDE_CMD_E6_SET_SLEEP_MODE = 0xE6,
  IDE_CMD_EC_IDENTIFY_DRIVE = 0xEC,
  IDE_CMD_E8_WRITE_BUFFER = 0xE8,
  IDE_CMD_E9_WRITE_SAME = 0xE9,
  IDE_CMD_EF_SET_FEATURES = 0xEF,
  IDE_CMD_F0_VENDOR_UNIQUE = 0xF0,
  IDE_CMD_F1_VENDOR_UNIQUE = 0xF1,
  IDE_CMD_F2_VENDOR_UNIQUE = 0xF2,
  IDE_CMD_F5_VENDOR_UNIQUE = 0xF5,
  IDE_CMD_F6_VENDOR_UNIQUE = 0xF6,
  IDE_CMD_F7_VENDOR_UNIQUE = 0xF7,
  IDE_CMD_F8_VENDOR_UNIQUE = 0xF8,
  IDE_CMD_F9_VENDOR_UNIQUE = 0xF9,
  IDE_CMD_FA_VENDOR_UNIQUE = 0xFA,
  IDE_CMD_FB_VENDOR_UNIQUE = 0xFB,
  IDE_CMD_FC_VENDOR_UNIQUE = 0xFC,
  IDE_CMD_FD_VENDOR_UNIQUE = 0xFD,
  IDE_CMD_FE_VENDOR_UNIQUE = 0xFE,
  IDE_CMD_FF_VENDOR_UNIQUE = 0xFF,
};

/* 124 */
typedef BDA_48h_Zenith_IDE_1F7h_Command IO_Port_1F7h_IDE_0_Command;

/* 125 */
enum __bitmask __bin __lzero IO_Port_1F7h_IDE_0_Status : unsigned __int8
{
  IO_Port_1F7h_IDE_0_Status_Busy = 0b10000000,
  IO_Port_1F7h_IDE_0_Status_Drive_ready = 0b01000000,
  IO_Port_1F7h_IDE_0_Status_Write_fault = 0b00100000,
  IO_Port_1F7h_IDE_0_Status_Seek_completed = 0b00010000,
  IO_Port_1F7h_IDE_0_Status_Data_Request_ready = 0b00001000,
  IO_Port_1F7h_IDE_0_Status_Corrected_data = 0b00000100,
  IO_Port_1F7h_IDE_0_Status_Index = 0b00000010,
  IO_Port_1F7h_IDE_0_Status_Error = 0b00000001,
};

/* 126 */
enum IO_Port_60h_KBD_Command : unsigned __int8
{
  IO_Port_60h_KBD_CMD_3A_Self_Test = 0x3A,
  IO_Port_60h_KBD_CMD_DD_A20_Disable = 0xDD,
  IO_Port_60h_KBD_CMD_DF_A20_Enable = 0xDF,
  IO_Port_60h_KBD_CMD_ED_SET_LEDS = 0xED,
  IO_Port_60h_KBD_CMD_EE_ECHO = 0xEE,
  IO_Port_60h_KBD_CMD_F0_SCAN_CODE_SET = 0xF0,
  IO_Port_60h_KBD_CMD_F2_ID_KEYBOARD = 0xF2,
  IO_Port_60h_KBD_CMD_F3_TYPEMATIC_RATE = 0xF3,
  IO_Port_60h_KBD_CMD_F4_ENABLE = 0xF4,
  IO_Port_60h_KBD_CMD_F5_DISABLE = 0xF5,
  IO_Port_60h_KBD_CMD_F6_SET_DEFAULT = 0xF6,
  IO_Port_60h_KBD_CMD_FE_RESEND = 0xFE,
  IO_Port_60h_KBD_CMD_FF_RESET_SELF_TEST = 0xFF,
};

/* 127 */
enum __bitmask __bin __lzero IO_Port_64h_KBC_Status : unsigned __int8
{
  IO_Port_64h_KBC_STAT_Parity_Error = 0b10000000,
  IO_Port_64h_KBC_STAT_Receive_Timeout = 0b01000000,
  IO_Port_64h_KBC_STAT_Transmit_Timeout = 0b00100000,
  IO_Port_64h_KBC_STAT_Inhibit = 0b00010000,
  IO_Port_64h_KBC_STAT_A2_Address_Line = 0b00001000,
  IO_Port_64h_KBC_STAT_Warm_boot = 0b00000100,
  IO_Port_64h_KBC_STAT_Input_Buffer_Full = 0b00000010,
  IO_Port_64h_KBC_STAT_Output_Buffer_Full = 0b00000001,
};

/* 128 */
enum IO_Port_64h_KBC_Command : unsigned __int8
{
  IO_Port_64h_KBC_CMD_20_READ_CONFIG = 0x20,
  IO_Port_64h_KBC_CMD_60_WRITE_CONFIG = 0x60,
  IO_Port_64h_KBC_CMD_AA_SELF_TEST = 0xAA,
  IO_Port_64h_KBC_CMD_AB_INTERFACE_TEST = 0xAB,
  IO_Port_64h_KBC_CMD_AD_DISABLE_KBD = 0xAD,
  IO_Port_64h_KBC_CMD_AE_ENABLE_KBD = 0xAE,
  IO_Port_64h_KBC_CMD_C0_READ_INPUT_PORT = 0xC0,
  IO_Port_64h_KBC_CMD_C0_READ_INPUT_PORT_Zenith = 0xC0,
  IO_Port_64h_KBC_CMD_D0_READ_OUTPUT_PORT = 0xD0,
  IO_Port_64h_KBC_CMD_D1_WRITE_OUTPUT_PORT = 0xD1,
  IO_Port_64h_KBC_CMD_FE_RESET_CPU = 0xFE,
  IO_Port_64h_KBC_CMD_B9_Zenith_Password_Version = 0xB9,
  IO_Port_64h_KBC_CMD_BA_Zenith_Password_Status = 0xBA,
  IO_Port_64h_KBC_CMD_BB_Zenith_Password_Command = 0xBB,
  IO_Port_64h_KBC_CMD_BC_Zenith_Password_Set = 0xBC,
};

/* 129 */
enum IO_Port_60h_KBD_Command_Status : unsigned __int8
{
  IO_Port_60h_KBC_Stat_55_SELF_TEST_OK = 0x55,
  IO_Port_60h_KBD_Stat_AA_RESET_SELF_TEST = 0xAA,
  IO_Port_60h_KBD_Stat_EA_Zenith_RESET_SELF_TEST = 0xEA,
  IO_Port_60h_KBD_Stat_EE_ECHO = 0xEE,
  IO_Port_60h_KBD_Stat_FA_ACK = 0xFA,
  IO_Port_60h_KBD_Stat_FC_SELF_TEST_FAIL = 0xFC,
  IO_Port_60h_KBD_Stat_FE_RESEND = 0xFE,
  IO_Port_60h_KBD_Zenith_Pass_Stat_FF_Pass_OK = 0xFF,
  IO_Port_60h_KBD_Zenith_Pass_Stat_0_Pass_enabled = 0x0,
  IO_Port_60h_KBD_Zenith_Pass_Stat_1_ = 0x1,
  IO_Port_60h_KBD_Zenith_Pass_Stat_2_Cant_Program = 0x2,
  IO_Port_60h_KBD_Zenith_Pass_Stat_3_No_pass_Support = 0x3,
  IO_Port_60h_KBD_Zenith_Pass_Stat_24_Version_supports_Pass = 0x24,
};

/* 130 */
enum __bitmask __bin __lzero BDA_17h_Keyboard_shift_flags_1 : unsigned __int8
{
  BDA_17h_flags_1_Right_SHIFT_DOWN = 0b00000001,
  BDA_17h_flags_1_Left_SHIFT_DOWN = 0b00000010,
  BDA_17h_flags_1_Ctrl_DOWN = 0b00000100,
  BDA_17h_flags_1_Alt_DOWN = 0b00001000,
  BDA_17h_flags_1_ScrollLock_STATE = 0b00010000,
  BDA_17h_flags_1_NumLock_STATE = 0b00100000,
  BDA_17h_flags_1_CapsLock_STATE = 0b01000000,
  BDA_17h_flags_1_Insert_STATE = 0b10000000,
};

/* 131 */
enum IVT_Video_Initialization_Table : unsigned __int8
{
  CRTC_IDX_HTOTAL = 0x0,
  CRTC_IDX_HDISPLAYED = 0x1,
  CRTC_IDX_HSYNC = 0x2,
  CRTC_IDX_HVSYNCWIDTH = 0x3,
  CRTC_IDX_VTOTAL = 0x4,
  CRTC_IDX_VTOTALADJUSTED = 0x5,
  CRTC_IDX_VDISPLAYED = 0x6,
  CRTC_IDX_VSYNC = 0x7,
  CRTC_IDX_INTERLACE = 0x8,
  CRTC_IDX_MAXSCANLINE = 0x9,
  CRTC_IDX_CURSORSTART = 0xA,
  CRTC_IDX_CURSOREND = 0xB,
};

/* 132 */
enum __bitmask __bin __lzero IO_Port_D6h_DMA2_Mode : unsigned __int8
{
  IO_Port_D6h_DMA2_Mode_CH_MASK = 0x03, ///< MASK
  IO_Port_D6h_DMA2_Mode_CH4 = 0b00000000,
  IO_Port_D6h_DMA2_Mode_CH5 = 0b00000001,
  IO_Port_D6h_DMA2_Mode_CH6 = 0b00000010,
  IO_Port_D6h_DMA2_Mode_CH7 = 0b00000011,
  IO_Port_D6h_DMA2_Mode_TYPE_MASK = 0x0C, ///< MASK
  IO_Port_D6h_DMA2_Mode_TYPE_Verify = 0b00000000,
  IO_Port_D6h_DMA2_Mode_TYPE_Write = 0b00000100,
  IO_Port_D6h_DMA2_Mode_TYPE_Read = 0b00001000,
  IO_Port_D6h_DMA2_Mode_TYPE_INVALID = 0b00001100,
  IO_Port_D6h_DMA2_Mode_AUTO_Init = 0b00010000,
  IO_Port_D6h_DMA2_Mode_ADDR_Dec = 0b00100000,
  IO_Port_D6h_DMA2_Mode_MASK = 0xC0,    ///< MASK
  IO_Port_D6h_DMA2_Mode_Demand = 0b00000000,
  IO_Port_D6h_DMA2_Mode_Single = 0b01000000,
  IO_Port_D6h_DMA2_Mode_Block = 0b10000000,
  IO_Port_D6h_DMA2_Mode_Cascade = 0b11000000,
};

/* 135 */
enum ASCII : unsigned __int8
{
  ASCII_NULL = 0x0,
  ASCII_SOH_Start_of_Heading = 0x1,
  ASCII_STX_Start_of_Text = 0x2,
  ASCII_ETX_End_of_Text = 0x3,
  ASCII_EOT_End_of_Transmission = 0x4,
  ASCII_ENQ = 0x5,
  ASCII_ACK = 0x6,
  ASCII_BELL = 0x7,
  ASCII_BACKSPACE = 0x8,
  ASCII_TAB = 0x9,
  ASCII_LF_Line_Feed = 0xA,
  ASCII_VT_Vertical_Tab = 0xB,
  ASCII_FF_Form_Feed = 0xC,
  ASCII_CR_ENTER = 0xD,
  ASCII_SO_Shift_Out = 0xE,
  ASCII_SI_Shift_In = 0xF,
  ASCII_DLE_Data_Link_Escape = 0x10,
  ASCII_DC1_XON = 0x11,
  ASCII_DC2 = 0x12,
  ASCII_DC3_XOFF = 0x13,
  ASCII_DC4 = 0x14,
  ASCII_NAK_Negative_Acknowledge = 0x15,
  ASCII_SYN_Synchronous_Idle = 0x16,
  ASCII_ETB_End_of_Transmission_Block = 0x17,
  ASCII_CAN_Cancel = 0x18,
  ASCII_EM_End_of_Medium = 0x19,
  ASCII_SUB_Substitute = 0x1A,
  ASCII_ESC = 0x1B,
  ASCII_FS_File_Separator = 0x1C,
  ASCII_GS_Group_Separator = 0x1D,
  ASCII_RS_Record_Separator = 0x1E,
  ASCII_US_Unit_Separator = 0x1F,
  ASCII_SPACE = 0x20,
  ASCII_0 = 0x30,
  ASCII_1 = 0x31,
  ASCII_2 = 0x32,
  ASCII_3 = 0x33,
  ASCII_4 = 0x34,
  ASCII_5 = 0x35,
  ASCII_6 = 0x36,
  ASCII_7 = 0x37,
  ASCII_8 = 0x38,
  ASCII_9 = 0x39,
  ASCII_DEL_Delete = 0x7F,
  ASCII_7Bit_MASK = 0x7F,
};

/* 136 */
enum IO_Port_80h_POST_Code
{
  POST_code_01_Zenith_VGA_check_clear_ram = 0x1,
  POST_code_02_Zenith_CGA_MDA_init = 0x2,
  POST_code_03_Zenith_MDA_CGA_clear_ram = 0x3,
  POST_code_05_Zenith_Stack_setup = 0x5,
  POST_code_07_Zenith_Ram_0E000_test = 0x7,
  POST_code_08_Zenith_Ram_0F000_test = 0x8,
  POST_code_09_Zenith_GDT_setup_shadow_VGA = 0x9,
  POST_code_0B_Zenith_KBC_setup = 0xB,
  POST_code_0C_Zenith_ColdWarm_Boot_check = 0xC,
  POST_code_0D_Zenith_Cold_Boot_Stack_setup = 0xD,
  POST_code_0E_Zenith_DMA_Page_init = 0xE,
  POST_code_0F_Zenith_DMA_PIT_init = 0xF,
  POST_code_10_Zenith_PIC_init = 0x10,
  POST_code_11_Zenith_Video_Bios_init = 0x11,
  POST_code_12_Zenith_CGA_MDA_init = 0x12,
  POST_code_13_Zenith_clear_screen_RTC_Ints = 0x13,
  POST_code_15_Zenith_CPU_test = 0x15,
  POST_code_16_Zenith_ROM_checksum_check = 0x16,
  POST_code_17_Zenith_SCP_failure_Reset = 0x17,
  POST_code_27_Zenith_Keyboard_init = 0x27,
  POST_code_39_Zenith_Ram_size_detect = 0x39,
  POST_code_3A_Zenith_Ram_test_or_init = 0x3A,
  POST_code_3C_Zenith_Ram_presence_check = 0x3C,
  POST_code_3D_Zenith_DMA_PIC_init = 0x3D,
};

/* 138 */
enum __bitmask __bin __lzero BDA_18h_Keyboard_shift_flags_2 : unsigned __int8
{
  BDA_18h_flags_2_Insert_PRESSED = 0b10000000,
  BDA_18h_flags_2_CapsLock_PRESSED = 0b01000000,
  BDA_18h_flags_2_NumLock_PRESSED = 0b00100000,
  BDA_18h_flags_2_ScrollLock_PRESSED = 0b00010000,
  BDA_18h_flags_2_Pause_ACTIVE = 0b00001000,
  BDA_18h_flags_2_SysReg_PRESSED = 0b00000100,
  BDA_18h_flags_2_Left_Alt_PRESSED = 0b00000010,
  BDA_18h_flags_2_Right_Alt_PRESSED = 0b00000001,
};

/* 141 */
enum __bitmask __bin __lzero IO_Port_3D8h_CRTC_Mode_Control : unsigned __int8
{
  IO_Port_3D8h_Mode_TEXT_80x25 = 0b00000001, ///< 1b = 80x25, 0b = 40x25
  IO_Port_3D8h_Mode_GRAPHICS = 0b00000010, ///< 1b = 320x200, 0b = Text
  IO_Port_3D8h_Mode_BW = 0b00000100,    ///< 1b = Black & White, 0b = Color
  IO_Port_3D8h_Mode_VIDEO_ENABLE = 0b00001000,
  IO_Port_3D8h_Mode_HI_RES_GRAPH = 0b00010000, ///< 1b = 640x200
  IO_Port_3D8h_Mode_BLINK_ENABLE = 0b00100000,
};

/* 139 */
typedef IO_Port_3D8h_CRTC_Mode_Control BDA_65h_CRTC_Mode_Control;

/* 140 */
enum __bitmask __bin __lzero IO_Port_3B8h_CRTC_Mode_Control_Mono : unsigned __int8
{
  IO_Port_3B8h_80x25_MDA_TEXT = 0b00000001,
  IO_Port_3B8h_MDA_VIDEO_ENABLE = 0b00001000,
  IO_Port_3B8h_MDA_BLINK_ENABLE = 0b00100000,
};

/* 142 */
enum __bitmask __bin __lzero IO_Port_3BAh_CRTC_Status_Mono : unsigned __int8
{
  IO_Port_3BAh_MONO_RETRACE = 0b00001000,
  IO_Port_3BAh_MONO_VIDEO_STIMULUS = 0b00000001,
};

/* 143 */
enum __bin __lzero IO_Port_3DAh_CRTC_Status : unsigned __int8
{
  IO_Port_3DAh_RETRACE = 0b00000001,
  IO_Port_3DAh_LPEN_TRIGGER = 0b00000010,
  IO_Port_3DAh_LPEN_SWITCH = 0b00000100,
  IO_Port_3DAh_VERT_RETRACE = 0b00001000,
  IO_Port_3DAh_CGA_FC0_read = 0b00010000,
  IO_Port_3DAh_CGA_FC1_read = 0b00100000,
  IO_Port_3DAh_EGA_FC0_write = 0b00000001,
  IO_Port_3DAh_EGA_FC1_write = 0b00000010,
};

/* 145 */
enum __lzero IO_Port_3D4h_CRTC_Index_CGA : unsigned __int8
{
  IO_Port_3D4h_CRTC_Idx_0_HORIZ_TOTAL = 0x00,
  IO_Port_3D4h_CRTC_Idx_1_HORIZ_DISPLAYED = 0x01,
  IO_Port_3D4h_CRTC_Idx_2_HORIZ_SYNC_POS = 0x02,
  IO_Port_3D4h_CRTC_Idx_3_HORIZ_SYNC_WIDTH = 0x03,
  IO_Port_3D4h_CRTC_Idx_4_VERT_TOTAL = 0x04,
  IO_Port_3D4h_CRTC_Idx_5_VERT_TOTAL_ADJUST = 0x05,
  IO_Port_3D4h_CRTC_Idx_6_VERT_DISPLAYED = 0x06,
  IO_Port_3D4h_CRTC_Idx_7_VERT_SYNC_POS = 0x07,
  IO_Port_3D4h_CRTC_Idx_8_INTERLACE_MODE = 0x08,
  IO_Port_3D4h_CRTC_Idx_9_MAX_SCANLINE_ADDR = 0x09,
  IO_Port_3D4h_CRTC_Idx_a_CURSOR_START = 0x0A,
  IO_Port_3D4h_CRTC_Idx_b_CURSOR_END = 0x0B,
  IO_Port_3D4h_CRTC_Idx_c_START_ADDR_H = 0x0C,
  IO_Port_3D4h_CRTC_Idx_d_START_ADDR_L = 0x0D,
  IO_Port_3D4h_CRTC_Idx_e_CURSOR_ADDR_H = 0x0E,
  IO_Port_3D4h_CRTC_Idx_f_CURSOR_ADDR_L = 0x0F,
  IO_Port_3D4h_CRTC_Idx_10_LIGHT_PEN_H = 0x10,
  IO_Port_3D4h_CRTC_Idx_11_LIGHT_PEN_L = 0x11,
};

/* 144 */
typedef IO_Port_3D4h_CRTC_Index_CGA IO_Port_3B4h_CRTC_Index_Mono;

/* 146 */
enum KEYBOARD_RESPONSES : unsigned __int8
{
  KBD_RES_AA_BAT_SUCCESS = 0xAA,        ///< Basic Assurance Test Passed
  KBD_RES_FC_BAT_FAILURE = 0xFC,        ///< Basic Assurance Test Failed
  KBD_RES_EE_ECHO = 0xEE,               ///< Echo response
  KBD_RES_FA_ACK = 0xFA,                ///< Acknowledge command
  KBD_RES_FE_RESEND = 0xFE,             ///< Resend last command
  KBD_PREFIX_E0_EXTENDED = 0xE0,
  KBD_PREFIX_E1_PAUSE = 0xE1,
  KBD_ID_AB_FIRST_BYTE = 0xAB,
  KBD_ID_83_MF2_STD = 0x83,             ///< Standard MF2 Keyboard [AB 83]
  KBD_ID_41_MF2_TRANS = 0x41,           ///< MF2 in Translation mode [AB 41]
};

/* 147 */
enum __bitmask __bin __lzero IO_Port_3D9h_CGA_Color_Control : unsigned __int8
{
  IO_Port_3D9h_BLUE_BORDER_BG = 0b00000001,
  IO_Port_3D9h_GREEN_BORDER_BG = 0b00000010,
  IO_Port_3D9h_RED_BORDER_BG = 0b00000100,
  IO_Port_3D9h_INTENSITY_ALT = 0b00001000,
  IO_Port_3D9h_ALT_INTENSITY_CLR = 0b00010000,
  IO_Port_3D9h_PALETTE_SELECT = 0b00100000, ///< 0 = Green/Red/Brown, 1 = Cyan/Magenta/White
};

/* 148 */
enum __bitmask __bin __lzero IO_Port_64h_KBC_CMD_WRITE_CONFIG : unsigned __int8
{
  KBC_CFG_KEYBOARD_INT_ENABLE = 0b00000001,
  KBC_CFG_MOUSE_INT_ENABLE = 0b00000010,
  KBC_CFG_SYSTEM_FLAG = 0b00000100,     ///< Bit 2: 1=System Passed POST, 0=Cold Reset
  KBC_CFG_INHIBIT_OVERRIDE = 0b00001000, ///< Bit 3: 1=Ignore Keyboard Lock Switch
  KBC_CFG_KEYBOARD_DISABLE = 0b00010000,
  KBC_CFG_MOUSE_DISABLE = 0b00100000,
  KBC_CFG_TRANSLATE_Set2_to_Set1 = 0b01000000,
};

/* 149 */
enum IO_Port_64h_KBC_CMD_BB_Zenith_Password_Command : unsigned __int8
{
  KBC_Zenith_Password_0_Enter = 0x0,
  KBC_Zenith_Password_1_unknown = 0x1,
  KBC_Zenith_Password_2_Check = 0x2,
  KBC_Zenith_Password_3_Change = 0x3,
  KBC_Zenith_Password_4_Verify = 0x4,
  KBC_Zenith_Password_5_unknown = 0x5,
};

/* 150 */
typedef IO_Port_3D9h_CGA_Color_Control BDA_66h_palette_or_CGA_color_burst;

/* 151 */
enum __bitmask __bin __lzero IO_Port_3F7h_FDC_Digital_Input_AT : unsigned __int8
{
  IO_Port_3F7h_FDC_DI_Drive0 = 0b00000001,
  IO_Port_3F7h_FDC_DI_Drive1 = 0b00000010,
  IO_Port_3F7h_FDC_DI_Head0 = 0b00000100,
  IO_Port_3F7h_FDC_DI_Head1 = 0b00001000,
  IO_Port_3F7h_FDC_DI_Head2 = 0b00010000,
  IO_Port_3F7h_FDC_DI_Head3 = 0b00100000,
  IO_Port_3F7h_FDC_DI_Write_Gate = 0b01000000,
  IO_Port_3F7h_FDC_DI_Disk_Changed = 0b10000000,
};

/* 152 */
enum __bitmask __bin __lzero IO_Port_3F2h_FDC_Digital_Output : unsigned __int8
{
  IO_Port_3F2h_FDC_DOR_DS_MASK = 0x03,  ///<  MASK
  IO_Port_3F2h_FDC_DOR_DS0 = 0b00000001,
  IO_Port_3F2h_FDC_DOR_DS1 = 0b00000010,
  IO_Port_3F2h_FDC_DOR_Enable = 0b00000100, ///< bit2 0=Reset Controller, 1=Enable Controller
  IO_Port_3F2h_FDC_DOR_DMA_INT = 0b00001000,
  IO_Port_3F2h_FDC_DOR_MOT_MASK = 0xF0, ///<  MASK
  IO_Port_3F2h_FDC_DOR_MOT0 = 0b00010000,
  IO_Port_3F2h_FDC_DOR_MOT1 = 0b00100000,
  IO_Port_3F2h_FDC_DOR_MOT2 = 0b01000000,
  IO_Port_3F2h_FDC_DOR_MOT3 = 0b10000000,
};

/* 153 */
enum __bitmask __bin __lzero IO_Port_3FBh_UART_Line_Control : unsigned __int8
{
  IO_Port_3FBh_UART_LCR_WLS_MASK = 0x03, ///< MASK
  IO_Port_3FBh_UART_LCR_WLS_6BIT = 0b00000001, ///< 0 = 5BIT
  IO_Port_3FBh_UART_LCR_WLS_7BIT = 0b00000010,
  IO_Port_3FBh_UART_LCR_WLS_8BIT = 0b00000011,
  IO_Port_3FBh_UART_LCR_Stop_Bit = 0b00000100, ///< Stop Bit (0=1 bit, 1=2 bits)
  IO_Port_3FBh_UART_LCR_Parity_MASK = 0x18, ///< MASK
  IO_Port_3FBh_UART_LCR_Odd_Parity = 0b00001000,
  IO_Port_3FBh_UART_LCR_Even_Parity = 0b00011000,
  IO_Port_3FBh_UART_LCR_No_Parity = 0b00010000, ///< 00 = No_Parity
  IO_Port_3FBh_UART_LCR_Stick_Parity = 0b00100000,
  IO_Port_3FBh_UART_LCR_Break_Control = 0b01000000,
  IO_Port_3FBh_UART_LCR_Div_Latch_Access_Bit = 0b10000000,
};

/* 154 */
enum __bitmask __bin __lzero IO_Port_3FAh_UART_Interrupt_Ident : unsigned __int8
{
  IO_Port_3FAh_UART_IIR_Int_PENDING = 0b00000001,
  IO_Port_3FAh_UART_IIR_Int_MASK = 0x0E, ///< MASK
  IO_Port_3FAh_UART_IIR_Int_MODEM = 0b00000000,
  IO_Port_3FAh_UART_IIR_Int_THRE = 0b00000010,
  IO_Port_3FAh_UART_IIR_Int_RDA = 0b00000100,
  IO_Port_3FAh_UART_IIR_Int_LSR = 0b00000110,
  IO_Port_3FAh_UART_IIR_Int_TIMEOUT = 0b00001100,
  IO_Port_3FAh_UART_IIR_FIFO_MASK = 0xC0, ///< MASK
  IO_Port_3FAh_UART_IIR_FIFO_NONE = 0b00000000,
  IO_Port_3FAh_UART_IIR_FIFO_UNUSABLE = 0b10000000,
  IO_Port_3FAh_UART_IIR_FIFO_ENABLED = 0b11000000,
};

/* 155 */
enum __bitmask __bin __lzero IO_Port_3F9h_UART_Interrupt_Enable : unsigned __int8
{
  IO_Port_3F9h_UART_IER_Received_Data_Available_Int = 0b00000001,
  IO_Port_3F9h_UART_IER_Transmitter_Holding_Register_Empty_Interrupt = 0b00000010,
  IO_Port_3F9h_UART_IER_Receiver_Line_Status_Interrupt = 0b00000100,
  IO_Port_3F9h_UART_IER_Modem_Status_Interrupt = 0b00001000,
};

/* 156 */
#pragma pack(push, 1)
struct LSB_MSB
{
  unsigned __int8 LSB __udec;
  unsigned __int8 MSB __udec;
};
#pragma pack(pop)

/* 157 */
enum __bitmask __bin __lzero IO_Port_3FCh_UART_Modem_Control : unsigned __int8
{
  IO_Port_3FCh_UART_MCR_DTR = 0b00000001,
  IO_Port_3FCh_UART_MCR_RTS = 0b00000010,
  IO_Port_3FCh_UART_MCR_OUT1 = 0b00000100,
  IO_Port_3FCh_UART_MCR_OUT2_Interrupts = 0b00001000,
  IO_Port_3FCh_UART_MCR_LOOPBACK = 0b00010000,
  IO_Port_3FCh_UART_MCR_Auto_Flow = 0b00100000,
};

/* 159 */
enum __bitmask __bin __lzero COM_Driver_Flags : unsigned __int8
{
  COM_Driver_FLG_RX_CHECK_DSR = 0b00000001,
  COM_Driver_FLG_SW_FLOW_CTRL = 0b00000010,
  COM_Driver_FLG_CHECK_DSR_XON = 0b00000100,
  COM_Driver_FLG_TX_BLOCKED = 0b00001000, ///< Bit 3: 1=Tx Suspended (Waiting for XON or waiting for ACK)
  COM_Driver_FLG_CHECK_CTS = 0b00010000,
  COM_Driver_FLG_CTS_POLARITY = 0b00100000,
};

/* 162 */
enum __bitmask __bin __lzero COM_Driver_Text_translation : unsigned __int8
{
  COM_Driver_TXT_RX_STRIP_8TH_BIT = 0b00000001,
  COM_Driver_TXT_TX_STRIP_8TH_BIT = 0b00000010,
  COM_Driver_TXT_RX_UPPERCASE = 0b00000100,
  COM_Driver_TXT_TX_UPPERCASE = 0b00001000,
};

/* 158 */
struct COM_Driver_Control_Block
{
  COM_Driver_Flags flags;
  COM_Driver_Text_translation Text_translation;
  unsigned __int8 CR_pad_char;
  unsigned __int8 CR_pad_count __udec;
  unsigned __int8 delay_reload;
  unsigned __int8 delay_counter;
  unsigned __int8 Init_params;
  unsigned __int8 timeout __udec;
};

/* 160 */
enum __bitmask __bin __lzero IO_Port_3FEh_UART_Modem_Status : unsigned __int8
{
  IO_Port_3FEh_UART_MSR_DELTA_MASK = 0x0F, ///< MASK
  IO_Port_3FEh_UART_MSR_DCTS = 0b00000001, ///< Delta Clear To Send (Changed since last read)
  IO_Port_3FEh_UART_MSR_DDSR = 0b00000010, ///< Delta Data Set Ready (Changed since last read)
  IO_Port_3FEh_UART_MSR_TERI = 0b00000100, ///< Trailing Edge Ring Indicator (Dropped from high to low)
  IO_Port_3FEh_UART_MSR_DDCD = 0b00001000, ///< Delta Data Carrier Detect (Changed since last read)
  IO_Port_3FEh_UART_MSR_CTS = 0b00010000,
  IO_Port_3FEh_UART_MSR_DSR = 0b00100000,
  IO_Port_3FEh_UART_MSR_RI = 0b01000000,
  IO_Port_3FEh_UART_MSR_DCD = 0b10000000,
};

/* 161 */
enum __bitmask __bin __lzero IO_Port_3FDh_UART_Line_Status : unsigned __int8
{
  IO_Port_3FDh_UART_LSR_DR_Data_Ready = 0b00000001,
  IO_Port_3FDh_UART_LSR_OE_Overrun_Error = 0b00000010,
  IO_Port_3FDh_UART_LSR_PE_Parity_Error = 0b00000100,
  IO_Port_3FDh_UART_LSR_FE_Framing_Error = 0b00001000,
  IO_Port_3FDh_UART_LSR_BI_Break_Interrupt = 0b00010000,
  IO_Port_3FDh_UART_LSR_THRE_Trans_Holding_Register_Empty = 0b00100000,
  IO_Port_3FDh_UART_LSR_TEMT_Trans_Empty = 0b01000000,
  IO_Port_3FDh_UART_LSR_FIFO_Error = 0b10000000,
};

/* 165 */
enum __bitmask __bin __lzero LPT_Driver_Flags : unsigned __int8
{
  LPT_Driver_REDIR_MASK = 0x0F,         ///< MASK
  LPT_Driver_REDIR_COM1 = 0b00000001,
  LPT_Driver_REDIR_COM2 = 0b00000010,
  LPT_Driver_REDIR_COM3 = 0b00000011,
  LPT_Driver_REDIR_COM4 = 0b00000100,
  LPT_Driver_STRIP_8TH_BIT = 0b00010000,
  LPT_Driver_UPPERCASE = 0b01000000,
};

/* 163 */
struct LPT_Driver_Control_Block
{
  LPT_Driver_Flags flags;
  unsigned __int8 CR_pad_char;
  unsigned __int8 CR_pad_count __udec;
  unsigned __int8 timeout __udec;
};

/* 164 */
enum __bitmask __bin __lzero IO_Port_379h_LPT1_Status : unsigned __int8
{
  IO_Port_379h_LPT_Status_TIMEOUT = 0b00000001,
  IO_Port_379h_LPT_Status_UNUSED_1 = 0b00000010,
  IO_Port_379h_LPT_Status_UNUSED_2 = 0b00000100,
  IO_Port_379h_LPT_Status_IO_ERROR = 0b00001000,
  IO_Port_379h_LPT_Status_SELECTED_online = 0b00010000,
  IO_Port_379h_LPT_Status_Out_of_paper = 0b00100000,
  IO_Port_379h_LPT_Status_ACK = 0b01000000,
  IO_Port_379h_LPT_Status_NOT_BUSY = 0b10000000,
};

/* 166 */
enum __bitmask __bin __lzero IO_Port_37Ah_LPT1_Control : unsigned __int8
{
  IO_Port_37Ah_LPT_Ctrl_STROBE = 0b00000001,
  IO_Port_37Ah_LPT_Ctrl_AUTO_FEED = 0b00000010,
  IO_Port_37Ah_LPT_Ctrl_INIT = 0b00000100,
  IO_Port_37Ah_LPT_Ctrl_SELECT_IN = 0b00001000,
  IO_Port_37Ah_LPT_Ctrl_IRQ_ENABLE = 0b00010000,
  IO_Port_37Ah_LPT_Ctrl_DIR_Read = 0b00100000,
  IO_Port_37Ah_LPT_Ctrl_RESERVED_1 = 0b01000000,
  IO_Port_37Ah_LPT_Ctrl_RESERVED_2 = 0b10000000,
};

/* 168 */
enum __bitmask __bin __lzero IO_Port_08h_DMA1_Status : unsigned __int8
{
  IO_Port_08h_DMA1_Status_CH0_Terminal_Count = 0b00000001,
  IO_Port_08h_DMA1_Status_CH1_Terminal_Count = 0b00000010,
  IO_Port_08h_DMA1_Status_CH2_Terminal_Count = 0b00000100,
  IO_Port_08h_DMA1_Status_CH3_Terminal_Count = 0b00001000,
  IO_Port_08h_DMA1_Status_CH0_Request_Pending = 0b00010000,
  IO_Port_08h_DMA1_Status_CH1_Request_Pending = 0b00100000,
  IO_Port_08h_DMA1_Status_CH2_Request_Pending = 0b01000000,
  IO_Port_08h_DMA1_Status_CH3_Request_Pending = 0b10000000,
};

/* 169 */
enum __bitmask __bin __lzero IO_Port_08h_DMA1_Command : unsigned __int8
{
  IO_Port_08h_DMA1_CMD_Memory_to_Memory = 0b00000001,
  IO_Port_08h_DMA1_CMD_CH0_Hold_Address = 0b00000010,
  IO_Port_08h_DMA1_Cmd_Disable_Controller = 0b00000100,
  IO_Port_08h_DMA1_Cmd_Compressed_Timing = 0b00001000,
  IO_Port_08h_DMA1_Cmd_Rotating_Priority = 0b00010000,
  IO_Port_08h_DMA1_Cmd_Extended_Write = 0b00100000,
  IO_Port_08h_DMA1_Cmd_DREQ_Sense_High = 0b01000000,
  IO_Port_08h_DMA1_Cmd_DACK_Sense_High = 0b10000000,
};

/* 170 */
enum __bitmask __bin __lzero IO_Port_0Ah_DMA1_Single_Mask : unsigned __int8
{
  IO_Port_0Ah_DMA1_SMask_CHANNEL_MASK = 0x03, ///< MASK
  IO_Port_0Ah_DMA1_SMask_Select_CH0 = 0b00000000,
  IO_Port_0Ah_DMA1_SMask_Select_CH1 = 0b00000001,
  IO_Port_0Ah_DMA1_SMask_Select_CH2 = 0b00000010,
  IO_Port_0Ah_DMA1_SMask_Select_CH3 = 0b00000011,
  IO_Port_0Ah_DMA1_SMask_SET_BIT = 0b00000100, ///< Mask channel (1=disable, 0=enable)
};

/* 171 */
enum __bitmask __bin __lzero IO_Port_0Fh_DMA1_Write_All_Mask : unsigned __int8
{
  IO_Port_0Fh_DMA1_AMask_CH0 = 0b00000001,
  IO_Port_0Fh_DMA1_AMask_CH1 = 0b00000010,
  IO_Port_0Fh_DMA1_AMask_CH2 = 0b00000100,
  IO_Port_0Fh_DMA1_AMask_CH3 = 0b00001000,
};

/* 172 */
enum __bitmask __bin __lzero IO_Port_D0h_DMA2_Status : unsigned __int8
{
  IO_Port_D0h_DMA2_Status_CH4_Terminal_Count = 0b00000001,
  IO_Port_D0h_DMA2_Status_CH5_Terminal_Count = 0b00000010,
  IO_Port_D0h_DMA2_Status_CH6_Terminal_Count = 0b00000100,
  IO_Port_D0h_DMA2_Status_CH7_Terminal_Count = 0b00001000,
  IO_Port_D0h_DMA2_Status_CH4_Request_Pending = 0b00010000,
  IO_Port_D0h_DMA2_Status_CH5_Request_Pending = 0b00100000,
  IO_Port_D0h_DMA2_Status_CH6_Request_Pending = 0b01000000,
  IO_Port_D0h_DMA2_Status_CH7_Request_Pending = 0b10000000,
};

/* 173 */
enum __bitmask __bin __lzero IO_Port_D0h_DMA2_Command : unsigned __int8
{
  IO_Port_D0h_DMA2_CMD_Memory_to_Memory = 0b00000001,
  IO_Port_D0h_DMA2_CMD_CH4_Hold_Address = 0b00000010,
  IO_Port_D0h_DMA2_Cmd_Disable_Controller = 0b00000100,
  IO_Port_D0h_DMA2_Cmd_Compressed_Timing = 0b00001000,
  IO_Port_D0h_DMA2_Cmd_Rotating_Priority = 0b00010000,
  IO_Port_D0h_DMA2_Cmd_Extended_Write = 0b00100000,
  IO_Port_D0h_DMA2_Cmd_DREQ_Sense_High = 0b01000000,
  IO_Port_D0h_DMA2_Cmd_DACK_Sense_High = 0b10000000,
};

/* 174 */
enum __bitmask __bin __lzero IO_Port_DEh_DMA2_Write_All_Mask : unsigned __int8
{
  IO_Port_DEh_DMA2_AMask_CH4 = 0b00000001,
  IO_Port_DEh_DMA2_AMask_CH5 = 0b00000010,
  IO_Port_DEh_DMA2_AMask_CH6 = 0b00000100,
  IO_Port_DEh_DMA2_AMask_CH7 = 0b00001000,
};

/* 175 */
enum __bitmask __bin __lzero IO_Port_D4h_DMA2_Single_Mask : unsigned __int8
{
  IO_Port_D4h_DMA2_SMask_CHANNEL_MASK = 0x03, ///< MASK
  IO_Port_D4h_DMA2_SMask_Select_CH4 = 0b00000000,
  IO_Port_D4h_DMA2_SMask_Select_CH5 = 0b00000001,
  IO_Port_D4h_DMA2_SMask_Select_CH6 = 0b00000010,
  IO_Port_D4h_DMA2_SMask_Select_CH7 = 0b00000011,
  IO_Port_D4h_DMA2_SMask_SET_BIT = 0b00000100, ///< Mask channel (1=disable, 0=enable)
};

/* 176 */
enum __bitmask __bin __lzero IO_Port_09h_DMA1_Write_Request : unsigned __int8
{
  IO_Port_09h_DMA1_REQ_CHANNEL_MASK = 0x03, ///< MASK
  IO_Port_09h_DMA1_REQ_Select_CH0 = 0b00000000,
  IO_Port_09h_DMA1_REQ_Select_CH1 = 0b00000001,
  IO_Port_09h_DMA1_REQ_Select_CH2 = 0b00000010,
  IO_Port_09h_DMA1_REQ_Select_CH3 = 0b00000011,
  IO_Port_09h_DMA1_REQ_SET_BIT = 0b00000100, ///< Set software request bit (0=clear)
};

/* 177 */
enum __bitmask __bin __lzero IO_Port_D2h_DMA2_Write_Request : unsigned __int8
{
  IO_Port_D2h_DMA2_REQ_CHANNEL_MASK = 0x03, ///< MASK
  IO_Port_D2h_DMA2_REQ_Select_CH4 = 0b00000000,
  IO_Port_D2h_DMA2_REQ_Select_CH5 = 0b00000001,
  IO_Port_D2h_DMA2_REQ_Select_CH6 = 0b00000010,
  IO_Port_D2h_DMA2_REQ_Select_CH7 = 0b00000011,
  IO_Port_D2h_DMA2_REQ_SET_BIT = 0b00000100, ///< Set software request bit (0=clear)
};

/* 178 */
enum __bitmask __bin __lzero IO_Port_3F6h_IDE_0_Alt_Status : unsigned __int8
{
  IO_Port_3F6h_Status_ERR = 0b00000001,
  IO_Port_3F6h_Status_IDX = 0b00000010,
  IO_Port_3F6h_Status_CORR = 0b00000100,
  IO_Port_3F6h_Status_DRQ = 0b00001000,
  IO_Port_3F6h_Status_DSC = 0b00010000,
  IO_Port_3F6h_Status_DF = 0b00100000,
  IO_Port_3F6h_Status_DRDY = 0b01000000,
  IO_Port_3F6h_Status_BSY = 0b10000000,
};

/* 179 */
enum __bitmask __bin __lzero IO_Port_3F6h_IDE_0_Dev_Control : unsigned __int8
{
  IO_Port_3F6h_Ctrl_RESERVED_0 = 0b00000001, ///< Reserved (Should be 0)
  IO_Port_3F6h_Ctrl_Disable_Interrupts = 0b00000010,
  IO_Port_3F6h_Ctrl_Software_Reset = 0b00000100,
  IO_Port_3F6h_Ctrl_HEAD_SEL_3_ENABLE = 0b00001000,
  IO_Port_3F6h_Ctrl_RESERVED_4 = 0b00010000, ///< Reserved (Should be 0)
  IO_Port_3F6h_Ctrl_RESERVED_5 = 0b00100000, ///< Reserved (Should be 0)
  IO_Port_3F6h_Ctrl_RESERVED_6 = 0b01000000, ///< Reserved (Should be 0)
  IO_Port_3F6h_Ctrl_RESERVED_7 = 0b10000000, ///< Reserved (Should be 0)
};

/* 180 */
enum __bitmask __bin __lzero IO_Port_43h_PIT_Control_Word : unsigned __int8
{
  IO_Port_43h_PIT_STYLE_MASK = 0x01,    ///< MASK
  IO_Port_43h_PIT_STYLE_Binary = 0b00000000, ///< Binary counter 16 bits
  IO_Port_43h_PIT_STYLE_BCD = 0b00000001, ///< BCD counter
  IO_Port_43h_PIT_MODE_MASK = 0x0E,     ///< MASK
  IO_Port_43h_PIT_MODE_0_Interrupt = 0b00000000, ///< Mode 0: Interrupt on terminal count
  IO_Port_43h_PIT_MODE_1_One_shot = 0b00000010, ///< Mode 1: Programmable one-shot
  IO_Port_43h_PIT_MODE_2 = 0b00000100,  ///< Mode 2: Rate generator (Bit 3 is don't care: x10)
  IO_Port_43h_PIT_MODE_3_Square = 0b00000110, ///< Mode 3: Square wave generator (Bit 3 is don't care: x11)
  IO_Port_43h_PIT_MODE_4 = 0b00001000,  ///< Mode 4: Software triggered strobe
  IO_Port_43h_PIT_MODE_5 = 0b00001010,  ///< Mode 5: Hardware triggered strobe
  IO_Port_43h_PIT_ACCESS_MASK = 0x30,   ///< MASK
  IO_Port_43h_PIT_ACCESS_LATCH = 0b00000000, ///< Counter latch command
  IO_Port_43h_PIT_ACCESS_LOW = 0b00010000, ///< Read/write counter bits 0-7 only
  IO_Port_43h_PIT_ACCESS_HIGH = 0b00100000, ///< Read/write counter bits 8-15 only
  IO_Port_43h_PIT_ACCESS_BOTH = 0b00110000, ///< Read/write counter bits 0-7 first, then 8-15
  IO_Port_43h_PIT_SELECT_MASK = 0xC0,   ///< MASK
  IO_Port_43h_PIT_SELECT_Counter0 = 0b00000000, ///< Counter 0 select
  IO_Port_43h_PIT_SELECT_Counter1 = 0b01000000, ///< Counter 1 select (not PS/2)
  IO_Port_43h_PIT_SELECT_Counter2 = 0b10000000, ///< Counter 2 select
};

/* 181 */
enum __bitmask __bin __lzero CMOS_1Eh_Zenith_COM_LPT : unsigned __int8
{
  CMOS_1Eh_Zenith_COM1_MASK = 0x03,     ///< MASK 0 = COM1_Disabled
  CMOS_1Eh_Zenith_COM1_3F8h = 0b00000001,
  CMOS_1Eh_Zenith_COM1_2F8h = 0b00000010,
  CMOS_1Eh_Zenith_COM1_2E8h = 0b00000011,
  CMOS_1Eh_Zenith_COM2_MASK = 0x0C,     ///< MASK 0 = COM2_Disabled
  CMOS_1Eh_Zenith_COM2_3F8h = 0b00000100,
  CMOS_1Eh_Zenith_COM2_2F8h = 0b00001000,
  CMOS_1Eh_Zenith_COM2_2E8h = 0b00001100,
  CMOS_1Eh_Zenith_LPT_MASK = 0x30,      ///< MASK 0 = LPT_Disabled
  CMOS_1Eh_Zenith_LPT_378h = 0b00010000,
  CMOS_1Eh_Zenith_LPT_278h = 0b00100000,
  CMOS_1Eh_Zenith_LPT_3BCh = 0b00110000,
};

/* 182 */
enum __bitmask __bin __lzero CMOS_1Fh_Zenith_ram_base_ext : unsigned __int8
{
  CMOS_1Fh_Zenith_ram_base_MASK = 0x07, ///< MASK
  CMOS_1Fh_Zenith_ram_base_256K = 0b00000001,
  CMOS_1Fh_Zenith_ram_base_512K = 0b00000010,
  CMOS_1Fh_Zenith_ram_base_640K = 0b00000100,
  CMOS_1Fh_Zenith_ram_ems_flag = 0b00001000,
  CMOS_1Fh_Zenith_ram_ems_idx_MASK = 0b01110000,
};

/* 183 */
struct ZBIOS_RowNode
{
  void *command_ptr __offset(OFF16|AUTO);
  void *next_node_ptr __offset(OFF16|AUTO);
};

/* 184 */
#pragma pack(push, 1)
struct ZBIOS_DrawCommand
{
  unsigned __int8 coord_X __udec;
  char character __strlit(C,"CP437");
  unsigned __int16 repeat_count __udec;
};
#pragma pack(pop)

/* 186 */
enum Keyboard_scancodes : unsigned __int16
{
  scancode_NULL = 0x0,
  scancode_Ctrl_C = 0x3,
  scancode_BACKSPACE = 0x8,
  scancode_TAB = 0x9,
  scancode_CR_ENTER = 0xD,
  scancode_Ctrl_S = 0x13,
  scancode_ESC = 0x1B,
  scancode_ESC_ = 0x11B,
  scancode_SPACE = 0x20,
  scancode_0 = 0x30,
  scancode_1 = 0x31,
  scancode_2 = 0x32,
  scancode_3 = 0x33,
  scancode_4 = 0x34,
  scancode_5 = 0x35,
  scancode_6 = 0x36,
  scancode_7 = 0x37,
  scancode_8 = 0x38,
  scancode_9 = 0x39,
  scancode_UP = 0x48,
  scancode_UP_ = 0x4800,
  scancode_LEFT = 0x4B,
  scancode_LEFT_ = 0x4B00,
  scancode_RIGHT = 0x4D,
  scancode_RIGHT_ = 0x4D00,
  scancode_DOWN = 0x50,
  scancode_DOWN_ = 0x5000,
  scancode_DEL = 0x53,
};

/* 185 */
struct scancode_char_pair
{
  ASCII ascii;
  Keyboard_scancodes scancode;
};

/* 188 */
struct __fixed(0x2) REG_ascii
{
  __at(0x0000) char upper __char;
  __at(0x0001) char lower __char;
};

/* 189 */
struct ZBIOS_Page
{
  void *Records_ptr __offset(OFF16|AUTO);
  void *Labels_ptr __offset(OFF16|AUTO);
  void *row_ptr[25] __offset(OFF16|AUTO);
  void *unknown_ptr __offset(OFF16|AUTO);
  void *Settings_ptr __offset(OFF16|AUTO);
};

/* 190 */
enum __bitmask __bin __lzero IO_Port_61h_FE3001A_Parity : unsigned __int8
{
  IO_Port_61h_FE3001A_Parity_Error = 0b10000000,
  IO_Port_61h_FE3001A_IO_CH_CHK_Error = 0b01000000,
  IO_Port_61h_FE3001A_IO_CH_CHK_Enable = 0b00001000,
  IO_Port_61h_FE3001A_ram_Parity_Enable = 0b00000100,
  IO_Port_61h_FE3001A_Tmr2data_AND_spkr_OFF = 0b00000010,
  IO_Port_61h_FE3001A_Tmr2gate_OR_spkr_ON = 0b00000001,
};

/* 191 */
enum __bitmask __bin __lzero IO_Port_3F7h_FDC_Config_Control : unsigned __int8
{
  IO_Port_3F7h_FDC_Conf_NOPREC = 0b00000100,
  IO_Port_3F7h_FDC_Conf_Rate_MASK = 0x03, ///< MASK
  IO_Port_3F7h_FDC_Conf_Rate_500KBPS = 0b00000000,
  IO_Port_3F7h_FDC_Conf_Rate_300KBPS = 0b00000001,
  IO_Port_3F7h_FDC_Conf_Rate_250KBPS = 0b00000010,
  IO_Port_3F7h_FDC_Conf_Rate_1MBPS = 0b00000011,
};

/* 192 */
enum __bitmask __bin __lzero IO_Port_64h_KBC_CMD_C0_READ_INPUT_PORT_Zenith : unsigned __int8
{
  IO_Port_64h_KBC_InPort_Zenith_Keyboard_Locked = 0b10000000,
};

/* 193 */
enum __bitmask __bin __lzero Zenith_cs46h_Video_capabilities : __int8
{
  Zenith_cs46h_No_CGA_Snow = 0b00100000,
  Zenith_cs46h_50ROW_Supported = 0b00010000,
  Zenith_cs46h_readable_Start_Address_regs = 0b00001000,
  Zenith_cs46h_is_CGA = 0b00000001,
};

/* 194 */
enum __bitmask __bin __lzero IO_Port_8Ch_Zenith_Diagnostic_LED : unsigned __int8
{
  IO_Port_8Ch_Zenith_CPU_LED = 0b00000001,
  IO_Port_8Ch_Zenith_ROM_LED = 0b00000010, ///< Rom Checksum
  IO_Port_8Ch_Zenith_RAM_LED = 0b00000100,
  IO_Port_8Ch_Zenith_INT_LED = 0b00001000, ///< Interrupt Timer
  IO_Port_8Ch_Zenith_DISK_LED = 0b00010000,
  IO_Port_8Ch_Zenith_READY_LED = 0b00100000,
  IO_Port_8Ch_Zenith_PARITY_LED = 0b01000000,
  IO_Port_8Ch_Zenith_D301_LED = 0b10000000,
};

/* 196 */
enum __bitmask __bin __lzero Zenith_cs404h_int13h_function_flags : __int8
{
  Zenith_cs404h_IDE_skip_taskfile = 0b10000000,
  Zenith_cs404h_IDE_wait_for_irq_completion = 0b01000000,
  Zenith_cs404h_IDE_No_Retry = 0b00100000,
  Zenith_cs404h_IDE_skip_ATA__communication = 0b00010000,
  Zenith_cs404h_IDE_Read = 0b00001000,
  Zenith_cs404h_IDE_Write = 0b00000100,
  Zenith_cs404h_2 = 0b00000010,
  Zenith_cs404h_1 = 0b00000001,
};

/* 197 */
enum Zenith_Slushware_RAM : __int16
{
  Zenith_cs3Ah_Framebuffer_offset = 0x3A,
  Zenith_cs47h_BDA_10h_equip_list_CMOS_0Eh_Diag_Status = 0x47, ///< high byte BDA, low byte CMOS
  Zenith_cs49h_BDA_segment = 0x49,
  Zenith_cs59h_some_BOOT_flags = 0x59,
  Zenith_csC6h_BDA_segment = 0xC6,
  Zenith_csCEh_Flags = 0xCE,
  Zenith_csCAh_BDA_80h_Keyboard_buffer_starting_address_UNUSED = 0xCA,
  Zenith_csCCh_BDA_82h_Keyboard_buffer_ending_address_UNUSED = 0xCC,
  Zenith_cs4C6h_BDA_80h_Keyboard_buffer_starting_address_UNUSED = 0x4C6,
  Zenith_cs4C8h_BDA_82h_Keyboard_buffer_ending_address_UNUSED = 0x4C8,
  Zenith_cs404h_int13h_function_flags = 0x404,
  Zenith_cs405h_int13h_function_request = 0x405, ///< comes from int 13 AH = function request number or 1B 1C in some extended int13 handler
  Zenith_cs406h_Joystick_store = 0x406,
  Zenith_cs40Eh_Expansion_Memory_Above_1MB = 0x40E,
  Zenith_cs410h_restore_state_Record_offset = 0x410,
  Zenith_cs412h_restore_state_stack_adjectment = 0x412,
  Zenith_cs416h_restore_state_DS = 0x416,
  Zenith_cs418h_restore_state_SI = 0x418,
  Zenith_cs41Ah_debugger_GDT = 0x41A,
  Zenith_cs4C5h_floppy_flags_maybe = 0x4C5,
  Zenith_cs4CAh_MFM_Tempest_bios_present = 0x4CA,
  Zenith_cs4CBh_floppy_init_writes_1_UNUSED = 0x4CB,
  Zenith_cs4CCh_ZBIOS_last_key_stroke_UNUSED = 0x4CC,
  Zenith_cs4CEh_IVT_Disk_Parameter_Table1 = 0x4CE,
  Zenith_cs4DEh_IVT_Disk_Parameter_Table2 = 0x4DE,
  Zenith_cs4EEh_HDD_flags = 0x4EE,
  Zenith_cs50Eh_DMA6_flags = 0x50E,
  Zenith_cs534h_int13h_6_status = 0x534,
  Zenith_cs53Fh_DMA_next_state_handler = 0x53F,
  Zenith_cs541h_DMA6_transfer_dispatch_table = 0x541,
  Zenith_cs544h_DMA6_Buffer_offset = 0x544,
  Zenith_cs546h_DMA6_Buffer_segment = 0x546,
  Zenith_cs548h_DMA6_Count = 0x548,
  Zenith_cs54Ah_DMA6_callback_handler_off = 0x54A,
  Zenith_cs54Ch_DMA6_callback_handler_seg = 0x54C,
  Zenith_cs54Eh_DMA6_Count_pending = 0x54E,
  Zenith_cs550h_A20_Disable = 0x550,
};

/* 198 */
enum __bitmask __bin __lzero IO_Port_3D4h_CRTC_Idx_5_Horiz_Retrace_End : __int8
{
  IO_Port_3D4h_CRTC_Idx_5_start_panning_odd_addr = 0b10000000, ///<  0=even
  IO_Port_3D4h_CRTC_Idx_5_retrace_delay = 0b01100000,
  IO_Port_3D4h_CRTC_Idx_5_H_Retrace_MASK = 0b00011111, ///<  MASK
};

/* 199 */
enum __lzero IO_Port_3D4h_CRTC_Index_EGAVGA : unsigned __int8
{
  IO_Port_3D4h_CRTC_Idx_0_Horiz_Total = 0x00,
  IO_Port_3D4h_CRTC_Idx_1_Horiz_DISPLAY_End = 0x01,
  IO_Port_3D4h_CRTC_Idx_2_Horiz_SYNC_POS = 0x02,
  IO_Port_3D4h_CRTC_Idx_3_Horiz_SYNC_WIDTH = 0x03,
  IO_Port_3D4h_CRTC_Idx_4_Horiz_Retrace_Start = 0x04,
  IO_Port_3D4h_CRTC_Idx_5_Horiz_Retrace_End = 0x05,
  IO_Port_3D4h_CRTC_Idx_6_Vertical_Total = 0x06,
  IO_Port_3D4h_CRTC_Idx_7_Overflow = 0x07,
  IO_Port_3D4h_CRTC_Idx_8_Preset_Row_Scan = 0x08,
  IO_Port_3D4h_CRTC_Idx_9_Max_Scan_Line = 0x09,
  IO_Port_3D4h_CRTC_Idx_a_Cursor_Start = 0x0A,
  IO_Port_3D4h_CRTC_Idx_b_Cursor_End = 0x0B,
  IO_Port_3D4h_CRTC_Idx_c_Start_ADDR_H = 0x0C,
  IO_Port_3D4h_CRTC_Idx_d_Start_ADDR_L = 0x0D,
  IO_Port_3D4h_CRTC_Idx_e_Cursor_ADDR_H = 0x0E,
  IO_Port_3D4h_CRTC_Idx_f_Cursor_ADDR_L = 0x0F,
  IO_Port_3D4h_CRTC_Idx_10r_LIGHT_PEN_H = 0x10,
  IO_Port_3D4h_CRTC_Idx_10w_Vertical_Retrace_Start = 0x10,
  IO_Port_3D4h_CRTC_Idx_11r_LIGHT_PEN_L = 0x11,
  IO_Port_3D4h_CRTC_Idx_11w_Vertical_Retrace_End = 0x11,
};

/* 200 */
enum __bitmask __bin __lzero Zenith_cs50Eh_DMA6_flags : __int16
{
  Zenith_cs50Eh_DMA6_flags_NEXT_DMA_WINDOW = 0b0000001000000000,
  Zenith_cs50Eh_DMA6_flags_NO_DMA_TRANSFER_maybe = 0b0000000100000000,
  Zenith_cs50Eh_DMA6_flags_VERIFY_MODE = 0b0000000000010000,
  Zenith_cs50Eh_DMA6_flags_ODD_BYTE_PENDING = 0b0000000000000100,
};

/* 201 */
enum __bitmask __bin __lzero Zenith_cs4EEh_HDD_flags : __int8
{
  Zenith_cs4EEh_HDD_present = 0b10000000,
  Zenith_cs4EEh_HDD_1_detected = 0b00000100,
  Zenith_cs4EEh_HDD_0_detected = 0b00000010,
  Zenith_cs4EEh_HDD_unknown = 0b00000001,
};

/* 202 */
enum boolean_variable : unsigned __int16
{
  True_bool = 0xFFFF,
  True_bool_ = 0x1,
  False_bool = 0x0,
};

/* 203 */
enum __bitmask __bin __lzero Zenith_csCEh_Flags : __int8
{
  Zenith_csCEh_b7_keyboard_irq_unused = 0b10000000,
  Zenith_csCEh_b3_cache_something = 0b00001000,
  Zenith_csCEh_b2_cache_enabled = 0b00000100,
  Zenith_csCEh_b1 = 0b00000010,
  Zenith_csCEh_b0_Backdoor = 0b00000001,
};

/* 204 */
enum __bitmask __bin __lzero Zenith_cs4C5h_floppy_flags_maybe : __int8
{
  Zenith_cs4C5h_b7 = 0b10000000,
  Zenith_cs4C5h_b6 = 0b01000000,
  Zenith_cs4C5h_b5 = 0b00100000,
  Zenith_cs4C5h_b4 = 0b00010000,
  Zenith_cs4C5h_b3 = 0b00001000,
  Zenith_cs4C5h_b2 = 0b00000100,
  Zenith_cs4C5h_b1 = 0b00000010,
  Zenith_cs4C5h_b0 = 0b00000001,
};

/* 205 */
enum Zenith_cs4CAh_MFM_Tempest_bios_present : unsigned __int8
{
  MFM_Tempest_bios_absent = 0x0,
  MFM_Tempest_bios_present = 0xFF,
};

